In [ ]:
# "indir" is a custom input path, and "outdir" is a custom output path.
# indir=""
outdir="../../../03.data/02.metainfo/01.Young_Mouse/"

In [1]:
regions <- c("CB","CTXsp","HPF","HY","Isocortex-1","Isocortex-2","MB","MY","OLF","PAL","P","STR","TH")
regions

 [1] "CB"          "CTXsp"       "HPF"         "HY"          "Isocortex-1"
 [6] "Isocortex-2" "MB"          "MY"          "OLF"         "PAL"
[11] "P"           "STR"         "TH"

In [2]:
terms <- NULL

In [ ]:
for(i in regions){
  object <- read.delim(sprintf("%s/%s_meta.txt",indir,i),header = T) 
  if(is.null(terms)){
    terms <- data.frame(region=i, object)
  }else{
    terms <- rbind(terms, data.frame(region=i, object))
  }
}

In [4]:
head(terms);dim(terms)

                           region cell_barcode     library_label
GTTGCGGCACTCCTTG-191_A01   CB     GTTGCGGCACTCCTTG L8TX_191217_01_G06
TCATTTGCAGAAGCTG-191_A01   CB     TCATTTGCAGAAGCTG L8TX_191217_01_G06
TTGTGGAAGTTACGGG-193_B01   CB     TTGTGGAAGTTACGGG L8TX_191217_01_E07
CATCCCACATGACCCG-221.2_B01 CB     CATCCCACATGACCCG L8TX_200220_01_H08
GCCTGTTCATCTCATT-191_B01   CB     GCCTGTTCATCTCATT L8TX_191217_01_H06
TACTTGTGTTACGGAG-213.2_B01 CB     TACTTGTGTTACGGAG L8TX_200206_01_A03
                           anatomical_division_label
GTTGCGGCACTCCTTG-191_A01   CB
TCATTTGCAGAAGCTG-191_A01   CB
TTGTGGAAGTTACGGG-193_B01   CB
CATCCCACATGACCCG-221.2_B01 CB
GCCTGTTCATCTCATT-191_B01   CB
TACTTGTGTTACGGAG-213.2_B01 CB
                           cell_new
GTTGCGGCACTCCTTG-191_A01   GTTGCGGCACTCCTTG-L8TX_191217_01_G06
TCATTTGCAGAAGCTG-191_A01   TCATTTGCAGAAGCTG-L8TX_191217_01_G06
TTGTGGAAGTTACGGG-193_B01   TTGTGGAAGTTACGGG-L8TX_191217_01_E07
CATCCCACATGACCCG-221.2_B01 CATCCCACATGACCCG-L8TX_200220_01_H08
GCCTGTTCATCTCATT-191_B01   GCCTGTTCATCTCATT-L8TX_191217_01_H06
TACTTGTGTTACGGAG-213.2_B01 TACTTGTGTTACGGAG-L8TX_200206_01_A03

[1] 2349544       5

In [5]:
length(unique(terms$region))
length(unique(terms$anatomical_division_label))

[1] 13

[1] 12

In [ ]:
metadata <- read.csv(sprintf("%s/cell_metadata.csv",indir))

In [7]:
head(metadata);dim(metadata)

  cell_label               cell_barcode     barcoded_cell_sample_label
1 GCGAGAAGTTAAGGGC-410_B05 GCGAGAAGTTAAGGGC 410_B05
2 AATGGCTCAGCTCCTT-411_B06 AATGGCTCAGCTCCTT 411_B06
3 AACACACGTTGCTTGA-410_B05 AACACACGTTGCTTGA 410_B05
4 CACAGATAGAGGCGGA-410_A05 CACAGATAGAGGCGGA 410_A05
5 AAAGTGAAGCATTTCG-410_B05 AAAGTGAAGCATTTCG 410_B05
6 GATCGTATCGAATCCA-411_B06 GATCGTATCGAATCCA 411_B06
  library_label      feature_matrix_label entity brain_section_label
1 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
2 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
3 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
4 L8TX_201029_01_A10 WMB-10Xv3-HPF        cell   NA
5 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
6 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
  library_method region_of_interest_acronym donor_label
1 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
2 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
3 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
4 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
5 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
6 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
  donor_genotype   donor_sex dataset_label x        y         cluster_alias
1 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.14683 -3.086639 1
2 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.13848 -3.022000 1
3 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.47256 -2.992709 1
4 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.37962 -3.043442 1
5 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.90948 -2.601536 1
6 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.49169 -2.945975 1

[1] 4042976      16

In [8]:
length(unique(metadata$cluster_alias))

[1] 5322

In [9]:
table(rownames(terms) %in% metadata$cell_label)

  FALSE    TRUE
   8194 2341350

In [10]:
metadata <- metadata[metadata$cell_label %in% rownames(terms),]

In [11]:
head(metadata);dim(metadata)

  cell_label               cell_barcode     barcoded_cell_sample_label
1 GCGAGAAGTTAAGGGC-410_B05 GCGAGAAGTTAAGGGC 410_B05
2 AATGGCTCAGCTCCTT-411_B06 AATGGCTCAGCTCCTT 411_B06
3 AACACACGTTGCTTGA-410_B05 AACACACGTTGCTTGA 410_B05
4 CACAGATAGAGGCGGA-410_A05 CACAGATAGAGGCGGA 410_A05
5 AAAGTGAAGCATTTCG-410_B05 AAAGTGAAGCATTTCG 410_B05
6 GATCGTATCGAATCCA-411_B06 GATCGTATCGAATCCA 411_B06
  library_label      feature_matrix_label entity brain_section_label
1 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
2 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
3 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
4 L8TX_201029_01_A10 WMB-10Xv3-HPF        cell   NA
5 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
6 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
  library_method region_of_interest_acronym donor_label
1 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
2 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
3 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
4 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
5 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
6 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
  donor_genotype   donor_sex dataset_label x        y         cluster_alias
1 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.14683 -3.086639 1
2 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.13848 -3.022000 1
3 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.47256 -2.992709 1
4 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.37962 -3.043442 1
5 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.90948 -2.601536 1
6 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.49169 -2.945975 1

[1] 2341350      16

In [12]:
metadata$cell_new <- terms$cell_new[match(metadata$cell_label,rownames(terms))]
metadata$region <- terms$region[match(metadata$cell_label,rownames(terms))]
head(metadata);dim(metadata)

  cell_label               cell_barcode     barcoded_cell_sample_label
1 GCGAGAAGTTAAGGGC-410_B05 GCGAGAAGTTAAGGGC 410_B05
2 AATGGCTCAGCTCCTT-411_B06 AATGGCTCAGCTCCTT 411_B06
3 AACACACGTTGCTTGA-410_B05 AACACACGTTGCTTGA 410_B05
4 CACAGATAGAGGCGGA-410_A05 CACAGATAGAGGCGGA 410_A05
5 AAAGTGAAGCATTTCG-410_B05 AAAGTGAAGCATTTCG 410_B05
6 GATCGTATCGAATCCA-411_B06 GATCGTATCGAATCCA 411_B06
  library_label      feature_matrix_label entity brain_section_label
1 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
2 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
3 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
4 L8TX_201029_01_A10 WMB-10Xv3-HPF        cell   NA
5 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
6 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
  library_method region_of_interest_acronym donor_label
1 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
2 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
3 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
4 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
5 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
6 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
  donor_genotype   donor_sex dataset_label x        y         cluster_alias
1 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.14683 -3.086639 1
2 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.13848 -3.022000 1
3 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.47256 -2.992709 1
4 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.37962 -3.043442 1
5 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.90948 -2.601536 1
6 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.49169 -2.945975 1
  cell_new                            region
1 GCGAGAAGTTAAGGGC-L8TX_201030_01_C12 HPF
2 AATGGCTCAGCTCCTT-L8TX_201029_01_E10 HPF
3 AACACACGTTGCTTGA-L8TX_201030_01_C12 HPF
4 CACAGATAGAGGCGGA-L8TX_201029_01_A10 HPF
5 AAAGTGAAGCATTTCG-L8TX_201030_01_C12 HPF
6 GATCGTATCGAATCCA-L8TX_201029_01_E10 HPF

[1] 2341350      18

In [ ]:
All <- read.delim(sprintf("%s/AIT17.0.metadata.init_submission_10Xv3.csv",indir),header = T,sep = ",") 
head(All);dim(All)

  sample_id                                      cl   library_prep
1 GTCGTAAGTGTTAACC-L8TX_190430_01_A08-1178164755  185 L8TX_190430_01_A08
2 CTACGGGGTCGAACAG-L8TX_200130_01_G02-1178484818 5231 L8TX_200130_01_G02
3 CGTTCTGGTGTTCGTA-L8TX_201113_01_D07-1177903936 3790 L8TX_201113_01_D07
4 AGGATCTTCACTCTTA-L8TX_201204_01_B02-1178468235 5252 L8TX_201204_01_B02
5 TGCACGGAGCTTTCTT-L8TX_201106_01_G03-1177903735 5230 L8TX_201106_01_G03
6 GCGAGAAGTGTATTCG-L8TX_201217_01_F06-1178469457 5231 L8TX_201217_01_F06
  doublet_score roi                   umi.counts qc.score method region_label
1 0.02197802    MOp                   11209      301.2897 10Xv3  MOp
2 0.02000000    MB - MRN-CUN-RN-RR-PN 10634      288.3003 10Xv3  MB
3 0.21333333    PONS - Pmot-Psat post 74257      453.4958 10Xv3  PONS
4 0.05000000    SS-GU-VISC             9161      249.3874 10Xv3  SS-GU-VISC
5 0.00000000    MB - VTA-SN           18585      257.0999 10Xv3  MB
6 0.08000000    HY LZ                 13470      282.1019 10Xv3  HY
  region_id sex external_donor_name age     platform     medical_conditions
1 15        F   457911              58 days 10X_cells_v3 Light
2 29        F   505950              66 days 10X_cells_v3 Light
3 30        M   551638              62 days 10X_cells_v3 Dark
4 18        M   553669              62 days 10X_cells_v3 Dark
5 29        M   551017              59 days 10X_cells_v3 Dark
6 26        M   556848              60 days 10X_cells_v3 Dark
  broad_region gene.counts
1 Pall         4161
2 MB           3432
3 HB           9545
4 Pall         3563
5 MB           4628
6 HY           4039

[1] 2349599      17

In [14]:
colnames(All)

 [1] "sample_id"           "cl"                  "library_prep"
 [4] "doublet_score"       "roi"                 "umi.counts"
 [7] "qc.score"            "method"              "region_label"
[10] "region_id"           "sex"                 "external_donor_name"
[13] "age"                 "platform"            "medical_conditions"
[16] "broad_region"        "gene.counts"

In [15]:
All$cell_new <- sub("-[^-]*$", "", All$sample_id)
head(All);dim(All)

  sample_id                                      cl   library_prep
1 GTCGTAAGTGTTAACC-L8TX_190430_01_A08-1178164755  185 L8TX_190430_01_A08
2 CTACGGGGTCGAACAG-L8TX_200130_01_G02-1178484818 5231 L8TX_200130_01_G02
3 CGTTCTGGTGTTCGTA-L8TX_201113_01_D07-1177903936 3790 L8TX_201113_01_D07
4 AGGATCTTCACTCTTA-L8TX_201204_01_B02-1178468235 5252 L8TX_201204_01_B02
5 TGCACGGAGCTTTCTT-L8TX_201106_01_G03-1177903735 5230 L8TX_201106_01_G03
6 GCGAGAAGTGTATTCG-L8TX_201217_01_F06-1178469457 5231 L8TX_201217_01_F06
  doublet_score roi                   umi.counts qc.score method region_label
1 0.02197802    MOp                   11209      301.2897 10Xv3  MOp
2 0.02000000    MB - MRN-CUN-RN-RR-PN 10634      288.3003 10Xv3  MB
3 0.21333333    PONS - Pmot-Psat post 74257      453.4958 10Xv3  PONS
4 0.05000000    SS-GU-VISC             9161      249.3874 10Xv3  SS-GU-VISC
5 0.00000000    MB - VTA-SN           18585      257.0999 10Xv3  MB
6 0.08000000    HY LZ                 13470      282.1019 10Xv3  HY
  region_id sex external_donor_name age     platform     medical_conditions
1 15        F   457911              58 days 10X_cells_v3 Light
2 29        F   505950              66 days 10X_cells_v3 Light
3 30        M   551638              62 days 10X_cells_v3 Dark
4 18        M   553669              62 days 10X_cells_v3 Dark
5 29        M   551017              59 days 10X_cells_v3 Dark
6 26        M   556848              60 days 10X_cells_v3 Dark
  broad_region gene.counts cell_new
1 Pall         4161        GTCGTAAGTGTTAACC-L8TX_190430_01_A08
2 MB           3432        CTACGGGGTCGAACAG-L8TX_200130_01_G02
3 HB           9545        CGTTCTGGTGTTCGTA-L8TX_201113_01_D07
4 Pall         3563        AGGATCTTCACTCTTA-L8TX_201204_01_B02
5 MB           4628        TGCACGGAGCTTTCTT-L8TX_201106_01_G03
6 HY           4039        GCGAGAAGTGTATTCG-L8TX_201217_01_F06

[1] 2349599      18

In [16]:
table(metadata$cell_new %in% All$cell_new)

  FALSE    TRUE
   4952 2336398

In [17]:
metadata <- metadata[metadata$cell_new %in% All$cell_new,]
head(metadata);dim(metadata)

  cell_label               cell_barcode     barcoded_cell_sample_label
1 GCGAGAAGTTAAGGGC-410_B05 GCGAGAAGTTAAGGGC 410_B05
2 AATGGCTCAGCTCCTT-411_B06 AATGGCTCAGCTCCTT 411_B06
3 AACACACGTTGCTTGA-410_B05 AACACACGTTGCTTGA 410_B05
4 CACAGATAGAGGCGGA-410_A05 CACAGATAGAGGCGGA 410_A05
5 AAAGTGAAGCATTTCG-410_B05 AAAGTGAAGCATTTCG 410_B05
6 GATCGTATCGAATCCA-411_B06 GATCGTATCGAATCCA 411_B06
  library_label      feature_matrix_label entity brain_section_label
1 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
2 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
3 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
4 L8TX_201029_01_A10 WMB-10Xv3-HPF        cell   NA
5 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
6 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
  library_method region_of_interest_acronym donor_label
1 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
2 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
3 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
4 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
5 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
6 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
  donor_genotype   donor_sex dataset_label x        y         cluster_alias
1 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.14683 -3.086639 1
2 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.13848 -3.022000 1
3 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.47256 -2.992709 1
4 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.37962 -3.043442 1
5 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.90948 -2.601536 1
6 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.49169 -2.945975 1
  cell_new                            region
1 GCGAGAAGTTAAGGGC-L8TX_201030_01_C12 HPF
2 AATGGCTCAGCTCCTT-L8TX_201029_01_E10 HPF
3 AACACACGTTGCTTGA-L8TX_201030_01_C12 HPF
4 CACAGATAGAGGCGGA-L8TX_201029_01_A10 HPF
5 AAAGTGAAGCATTTCG-L8TX_201030_01_C12 HPF
6 GATCGTATCGAATCCA-L8TX_201029_01_E10 HPF

[1] 2336398      18

In [18]:
metadata$region_label <- All$region_label[match(metadata$cell_new,All$cell_new)]
head(metadata);dim(metadata)

  cell_label               cell_barcode     barcoded_cell_sample_label
1 GCGAGAAGTTAAGGGC-410_B05 GCGAGAAGTTAAGGGC 410_B05
2 AATGGCTCAGCTCCTT-411_B06 AATGGCTCAGCTCCTT 411_B06
3 AACACACGTTGCTTGA-410_B05 AACACACGTTGCTTGA 410_B05
4 CACAGATAGAGGCGGA-410_A05 CACAGATAGAGGCGGA 410_A05
5 AAAGTGAAGCATTTCG-410_B05 AAAGTGAAGCATTTCG 410_B05
6 GATCGTATCGAATCCA-411_B06 GATCGTATCGAATCCA 411_B06
  library_label      feature_matrix_label entity brain_section_label
1 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
2 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
3 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
4 L8TX_201029_01_A10 WMB-10Xv3-HPF        cell   NA
5 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
6 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
  library_method region_of_interest_acronym donor_label
1 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
2 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
3 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
4 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
5 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850
6 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851
  donor_genotype   donor_sex dataset_label x        y         cluster_alias
1 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.14683 -3.086639 1
2 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.13848 -3.022000 1
3 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.47256 -2.992709 1
4 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.37962 -3.043442 1
5 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.90948 -2.601536 1
6 Ai14(RCL-tdT)/wt F         WMB-10Xv3     23.49169 -2.945975 1
  cell_new                            region region_label
1 GCGAGAAGTTAAGGGC-L8TX_201030_01_C12 HPF    RHP
2 AATGGCTCAGCTCCTT-L8TX_201029_01_E10 HPF    RHP
3 AACACACGTTGCTTGA-L8TX_201030_01_C12 HPF    RHP
4 CACAGATAGAGGCGGA-L8TX_201029_01_A10 HPF    RHP
5 AAAGTGAAGCATTTCG-L8TX_201030_01_C12 HPF    RHP
6 GATCGTATCGAATCCA-L8TX_201029_01_E10 HPF    RHP

[1] 2336398      19

In [19]:
library(readxl)

In [ ]:
cl <- read_excel(sprintf("%s/cl.df_CCN202307220_new.xlsx",indir),sheet = 1) 
head(cl);dim(cl)

New names:
• `CTX.subclass_id` -> `CTX.subclass_id...38`
• `CTX.subclass_id` -> `CTX.subclass_id...39`

  cl  cluster_id cluster_id_label             supertype_id
1 128 1          0001 CLA-EPd-CTX Car3 Glut_1 1
2 129 2          0002 CLA-EPd-CTX Car3 Glut_1 1
3 130 3          0003 CLA-EPd-CTX Car3 Glut_1 1
4 143 4          0004 CLA-EPd-CTX Car3 Glut_1 1
5 131 5          0005 CLA-EPd-CTX Car3 Glut_2 2
6 116 6          0006 IT EP-CLA Glut_1        3
  supertype_label         supertype_id_label           subclass_id
1 CLA-EPd-CTX Car3 Glut_1 0001 CLA-EPd-CTX Car3 Glut_1 1
2 CLA-EPd-CTX Car3 Glut_1 0001 CLA-EPd-CTX Car3 Glut_1 1
3 CLA-EPd-CTX Car3 Glut_1 0001 CLA-EPd-CTX Car3 Glut_1 1
4 CLA-EPd-CTX Car3 Glut_1 0001 CLA-EPd-CTX Car3 Glut_1 1
5 CLA-EPd-CTX Car3 Glut_2 0002 CLA-EPd-CTX Car3 Glut_2 1
6 IT EP-CLA Glut_1        0003 IT EP-CLA Glut_1        2
  subclass_label        subclass_id_label         class_id ⋯
1 CLA-EPd-CTX Car3 Glut 001 CLA-EPd-CTX Car3 Glut 1        ⋯
2 CLA-EPd-CTX Car3 Glut 001 CLA-EPd-CTX Car3 Glut 1        ⋯
3 CLA-EPd-CTX Car3 Glut 001 CLA-EPd-CTX Car3 Glut 1        ⋯
4 CLA-EPd-CTX Car3 Glut 001 CLA-EPd-CTX Car3 Glut 1        ⋯
5 CLA-EPd-CTX Car3 Glut 001 CLA-EPd-CTX Car3 Glut 1        ⋯
6 IT EP-CLA Glut        002 IT EP-CLA Glut        1        ⋯
  CTX.subclass_id...38 CTX.subclass_id...39 CTX.neighborhood_id
1 21                   Car3                 4
2 21                   Car3                 4
3 21                   Car3                 4
4 21                   Car3                 4
5 21                   Car3                 4
6 19                   L6 IT CTX            4
  CTX.neighborhood_label CTX.size taxonomy_id  cell_set_accession.cluster
1 L4_5_6_IT_Car3         1937     CCN202307220 CS20230722_CLUS_0001
2 L4_5_6_IT_Car3         1712     CCN202307220 CS20230722_CLUS_0002
3 L4_5_6_IT_Car3         9576     CCN202307220 CS20230722_CLUS_0003
4 L4_5_6_IT_Car3         7469     CCN202307220 CS20230722_CLUS_0004
5 L4_5_6_IT_Car3          360     CCN202307220 CS20230722_CLUS_0005
6 L4_5_6_IT_Car3         1283     CCN202307220 CS20230722_CLUS_0006
  cell_set_accession.supertype cell_set_accession.subclass
1 CS20230722_SUPT_0001         CS20230722_SUBC_001
2 CS20230722_SUPT_0001         CS20230722_SUBC_001
3 CS20230722_SUPT_0001         CS20230722_SUBC_001
4 CS20230722_SUPT_0001         CS20230722_SUBC_001
5 CS20230722_SUPT_0002         CS20230722_SUBC_001
6 CS20230722_SUPT_0003         CS20230722_SUBC_002
  cell_set_accession.class
1 CS20230722_CLAS_01
2 CS20230722_CLAS_01
3 CS20230722_CLAS_01
4 CS20230722_CLAS_01
5 CS20230722_CLAS_01
6 CS20230722_CLAS_01

[1] 5322   47

In [21]:
length(unique(cl$cluster_id))

[1] 5322

In [22]:
colnames(cl)

 [1] "cl"
 [2] "cluster_id"
 [3] "cluster_id_label"
 [4] "supertype_id"
 [5] "supertype_label"
 [6] "supertype_id_label"
 [7] "subclass_id"
 [8] "subclass_label"
 [9] "subclass_id_label"
[10] "class_id"
[11] "class_label"
[12] "class_id_label"
[13] "neighborhood"
[14] "anatomical_annotation"
[15] "notes"
[16] "CCF_broad.freq"
[17] "CCF_acronym.freq"
[18] "v3.size"
[19] "v2.size"
[20] "multiome.size"
[21] "F"
[22] "M"
[23] "sex.bias"
[24] "Dark"
[25] "Light"
[26] "nt_type_label"
[27] "nt.markers"
[28] "nt_type_combo_label"
[29] "np.markers"
[30] "cluster.markers.combo"
[31] "merfish.markers.combo"
[32] "cluster.TF.markers.combo"
[33] "cluster.markers.combo (within subclass)"
[34] "CTX.cluster_id"
[35] "CTX.cluster_label"
[36] "CTX.supertype_id"
[37] "CTX.supertype_label"
[38] "CTX.subclass_id...38"
[39] "CTX.subclass_id...39"
[40] "CTX.neighborhood_id"
[41] "CTX.neighborhood_label"
[42] "CTX.size"
[43] "taxonomy_id"
[44] "cell_set_accession.cluster"
[45] "cell_set_accession.supertype"
[46] "cell_set_accession.subclass"
[47] "cell_set_accession.class"

In [23]:
cl_class <- cl[,c("cl","class_label","subclass_label")]
head(cl_class);dim(cl_class)

  cl  class_label subclass_label
1 128 IT-ET Glut  CLA-EPd-CTX Car3 Glut
2 129 IT-ET Glut  CLA-EPd-CTX Car3 Glut
3 130 IT-ET Glut  CLA-EPd-CTX Car3 Glut
4 143 IT-ET Glut  CLA-EPd-CTX Car3 Glut
5 131 IT-ET Glut  CLA-EPd-CTX Car3 Glut
6 116 IT-ET Glut  IT EP-CLA Glut

[1] 5322    3

In [24]:
metadata$class_label <- cl_class$class_label[match(metadata$cluster_alias,cl_class$cl)]
metadata$subclass_label <- cl_class$subclass_label[match(metadata$cluster_alias,cl_class$cl)]

In [25]:
head(metadata);dim(metadata)

  cell_label               cell_barcode     barcoded_cell_sample_label
1 GCGAGAAGTTAAGGGC-410_B05 GCGAGAAGTTAAGGGC 410_B05
2 AATGGCTCAGCTCCTT-411_B06 AATGGCTCAGCTCCTT 411_B06
3 AACACACGTTGCTTGA-410_B05 AACACACGTTGCTTGA 410_B05
4 CACAGATAGAGGCGGA-410_A05 CACAGATAGAGGCGGA 410_A05
5 AAAGTGAAGCATTTCG-410_B05 AAAGTGAAGCATTTCG 410_B05
6 GATCGTATCGAATCCA-411_B06 GATCGTATCGAATCCA 411_B06
  library_label      feature_matrix_label entity brain_section_label
1 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
2 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
3 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
4 L8TX_201029_01_A10 WMB-10Xv3-HPF        cell   NA
5 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
6 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
  library_method region_of_interest_acronym donor_label                  ⋯
1 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850 ⋯
2 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851 ⋯
3 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850 ⋯
4 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850 ⋯
5 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850 ⋯
6 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851 ⋯
  donor_sex dataset_label x        y         cluster_alias
1 F         WMB-10Xv3     23.14683 -3.086639 1
2 F         WMB-10Xv3     23.13848 -3.022000 1
3 F         WMB-10Xv3     23.47256 -2.992709 1
4 F         WMB-10Xv3     23.37962 -3.043442 1
5 F         WMB-10Xv3     23.90948 -2.601536 1
6 F         WMB-10Xv3     23.49169 -2.945975 1
  cell_new                            region region_label class_label
1 GCGAGAAGTTAAGGGC-L8TX_201030_01_C12 HPF    RHP          IT-ET Glut
2 AATGGCTCAGCTCCTT-L8TX_201029_01_E10 HPF    RHP          IT-ET Glut
3 AACACACGTTGCTTGA-L8TX_201030_01_C12 HPF    RHP          IT-ET Glut
4 CACAGATAGAGGCGGA-L8TX_201029_01_A10 HPF    RHP          IT-ET Glut
5 AAAGTGAAGCATTTCG-L8TX_201030_01_C12 HPF    RHP          IT-ET Glut
6 GATCGTATCGAATCCA-L8TX_201029_01_E10 HPF    RHP          IT-ET Glut
  subclass_label
1 L2 IT PPP-APr Glut
2 L2 IT PPP-APr Glut
3 L2 IT PPP-APr Glut
4 L2 IT PPP-APr Glut
5 L2 IT PPP-APr Glut
6 L2 IT PPP-APr Glut

[1] 2336398      21

In [26]:
library(dplyr)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [27]:
table(is.na(metadata$class_label))
table(is.na(metadata$subclass_label))

  FALSE
2336398

  FALSE
2336398

In [28]:
length(unique(metadata$subclass_label))

[1] 334

In [29]:
grep("Astro",unique(metadata$subclass_label),value = T)

[1] "Astro-TE NN"       "Astroependymal NN" "Astro-OLF NN"
[4] "Astro-NT NN"       "Astro-CB NN"

In [30]:
length(unique(cl$subclass_label))

[1] 338

In [31]:
unique(cl$subclass_label)[!unique(cl$subclass_label) %in% unique(metadata$subclass_label)]

[1] "RN Spp1 Glut"         "PSV Pax2 Gly-Gaba"    "NLL-po Pax7 Gaba"
[4] "CU-ECU Pax2 Gly-Gaba"

In [32]:
head(terms);dim(terms)

                           region cell_barcode     library_label
GTTGCGGCACTCCTTG-191_A01   CB     GTTGCGGCACTCCTTG L8TX_191217_01_G06
TCATTTGCAGAAGCTG-191_A01   CB     TCATTTGCAGAAGCTG L8TX_191217_01_G06
TTGTGGAAGTTACGGG-193_B01   CB     TTGTGGAAGTTACGGG L8TX_191217_01_E07
CATCCCACATGACCCG-221.2_B01 CB     CATCCCACATGACCCG L8TX_200220_01_H08
GCCTGTTCATCTCATT-191_B01   CB     GCCTGTTCATCTCATT L8TX_191217_01_H06
TACTTGTGTTACGGAG-213.2_B01 CB     TACTTGTGTTACGGAG L8TX_200206_01_A03
                           anatomical_division_label
GTTGCGGCACTCCTTG-191_A01   CB
TCATTTGCAGAAGCTG-191_A01   CB
TTGTGGAAGTTACGGG-193_B01   CB
CATCCCACATGACCCG-221.2_B01 CB
GCCTGTTCATCTCATT-191_B01   CB
TACTTGTGTTACGGAG-213.2_B01 CB
                           cell_new
GTTGCGGCACTCCTTG-191_A01   GTTGCGGCACTCCTTG-L8TX_191217_01_G06
TCATTTGCAGAAGCTG-191_A01   TCATTTGCAGAAGCTG-L8TX_191217_01_G06
TTGTGGAAGTTACGGG-193_B01   TTGTGGAAGTTACGGG-L8TX_191217_01_E07
CATCCCACATGACCCG-221.2_B01 CATCCCACATGACCCG-L8TX_200220_01_H08
GCCTGTTCATCTCATT-191_B01   GCCTGTTCATCTCATT-L8TX_191217_01_H06
TACTTGTGTTACGGAG-213.2_B01 TACTTGTGTTACGGAG-L8TX_200206_01_A03

[1] 2349544       5

In [33]:
table(terms$cell_new %in% metadata$cell_new)

  FALSE    TRUE
  13146 2336398

In [34]:
head(metadata);dim(metadata)

  cell_label               cell_barcode     barcoded_cell_sample_label
1 GCGAGAAGTTAAGGGC-410_B05 GCGAGAAGTTAAGGGC 410_B05
2 AATGGCTCAGCTCCTT-411_B06 AATGGCTCAGCTCCTT 411_B06
3 AACACACGTTGCTTGA-410_B05 AACACACGTTGCTTGA 410_B05
4 CACAGATAGAGGCGGA-410_A05 CACAGATAGAGGCGGA 410_A05
5 AAAGTGAAGCATTTCG-410_B05 AAAGTGAAGCATTTCG 410_B05
6 GATCGTATCGAATCCA-411_B06 GATCGTATCGAATCCA 411_B06
  library_label      feature_matrix_label entity brain_section_label
1 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
2 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
3 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
4 L8TX_201029_01_A10 WMB-10Xv3-HPF        cell   NA
5 L8TX_201030_01_C12 WMB-10Xv3-HPF        cell   NA
6 L8TX_201029_01_E10 WMB-10Xv3-HPF        cell   NA
  library_method region_of_interest_acronym donor_label                  ⋯
1 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850 ⋯
2 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851 ⋯
3 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850 ⋯
4 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850 ⋯
5 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550850 ⋯
6 10Xv3          RHP                        Snap25-IRES2-Cre;Ai14-550851 ⋯
  donor_sex dataset_label x        y         cluster_alias
1 F         WMB-10Xv3     23.14683 -3.086639 1
2 F         WMB-10Xv3     23.13848 -3.022000 1
3 F         WMB-10Xv3     23.47256 -2.992709 1
4 F         WMB-10Xv3     23.37962 -3.043442 1
5 F         WMB-10Xv3     23.90948 -2.601536 1
6 F         WMB-10Xv3     23.49169 -2.945975 1
  cell_new                            region region_label class_label
1 GCGAGAAGTTAAGGGC-L8TX_201030_01_C12 HPF    RHP          IT-ET Glut
2 AATGGCTCAGCTCCTT-L8TX_201029_01_E10 HPF    RHP          IT-ET Glut
3 AACACACGTTGCTTGA-L8TX_201030_01_C12 HPF    RHP          IT-ET Glut
4 CACAGATAGAGGCGGA-L8TX_201029_01_A10 HPF    RHP          IT-ET Glut
5 AAAGTGAAGCATTTCG-L8TX_201030_01_C12 HPF    RHP          IT-ET Glut
6 GATCGTATCGAATCCA-L8TX_201029_01_E10 HPF    RHP          IT-ET Glut
  subclass_label
1 L2 IT PPP-APr Glut
2 L2 IT PPP-APr Glut
3 L2 IT PPP-APr Glut
4 L2 IT PPP-APr Glut
5 L2 IT PPP-APr Glut
6 L2 IT PPP-APr Glut

[1] 2336398      21

In [35]:
zeng_v3_metadata <- metadata %>% dplyr::select(cluster_alias,cell_new,region,region_label,class_label,subclass_label)
head(zeng_v3_metadata);dim(zeng_v3_metadata)

  cluster_alias cell_new                            region region_label
1 1             GCGAGAAGTTAAGGGC-L8TX_201030_01_C12 HPF    RHP
2 1             AATGGCTCAGCTCCTT-L8TX_201029_01_E10 HPF    RHP
3 1             AACACACGTTGCTTGA-L8TX_201030_01_C12 HPF    RHP
4 1             CACAGATAGAGGCGGA-L8TX_201029_01_A10 HPF    RHP
5 1             AAAGTGAAGCATTTCG-L8TX_201030_01_C12 HPF    RHP
6 1             GATCGTATCGAATCCA-L8TX_201029_01_E10 HPF    RHP
  class_label subclass_label
1 IT-ET Glut  L2 IT PPP-APr Glut
2 IT-ET Glut  L2 IT PPP-APr Glut
3 IT-ET Glut  L2 IT PPP-APr Glut
4 IT-ET Glut  L2 IT PPP-APr Glut
5 IT-ET Glut  L2 IT PPP-APr Glut
6 IT-ET Glut  L2 IT PPP-APr Glut

[1] 2336398       6

In [ ]:
saveRDS(zeng_v3_metadata,sprintf("%s/01-zeng_10xV3_metadata_final.rds",outdir))

In [37]:
unique(zeng_v3_metadata$region_label)

 [1] "RHP"              "RSP"              "ACA"              "PL-ILA-ORB"
 [5] "AUD-TEa-PERI-ECT" "SS-GU-VISC"       "MO-FRP"           "PAL"
 [9] "sAMY"             "CTXsp"            "HY"               "STRv"
[13] "OLF"              "LSX"              "AI"               "STRd"
[17] "VIS-PTLp"         "VIS"              "TH"               "MOp"
[21] "ENT"              "HIP"              "PONS"             "MB"
[25] "MY"               "CB"

In [38]:
unique(zeng_v3_metadata$region)

 [1] "HPF"         "Isocortex-1" "PAL"         "STR"         "CTXsp"
 [6] "HY"          "OLF"         "TH"          "P"           "MB"
[11] "MY"          "CB"          "Isocortex-2"

In [39]:
reserved_region <- c("MO-FRP", "MOp", "SS-GU-VISC", "AUD-TEa-PERI-ECT", "VIS-PTLp", "VIS", "ACA", "PL-ILA-ORB", "AI", "RSP", "OLF", "HIP", "STRd", "STRv")
reserved_region
length(reserved_region)

 [1] "MO-FRP"           "MOp"              "SS-GU-VISC"       "AUD-TEa-PERI-ECT"
 [5] "VIS-PTLp"         "VIS"              "ACA"              "PL-ILA-ORB"
 [9] "AI"               "RSP"              "OLF"              "HIP"
[13] "STRd"             "STRv"

[1] 14

In [40]:
table(reserved_region %in% zeng_v3_metadata$region_label)

TRUE
  14

In [41]:
zeng_v3_metadata_filter <- zeng_v3_metadata[zeng_v3_metadata$region_label %in% reserved_region,]
head(zeng_v3_metadata_filter);dim(zeng_v3_metadata_filter)

    cluster_alias cell_new                            region      region_label
211  10           GCACTAAGTACAAGTA-L8TX_201022_01_H06 Isocortex-1 RSP
289  10           CAGAGCCGTCCTGGTG-L8TX_201023_01_A09 Isocortex-1 RSP
316  10           CGCCATTCACGACAGA-L8TX_201022_01_B07 Isocortex-1 RSP
376  10           GGGTTTATCCGATCGG-L8TX_201022_01_H06 Isocortex-1 RSP
397  10           GTGTGATCAGACAAAT-L8TX_201022_01_H06 Isocortex-1 RSP
456 100           TGCAGATCATCAGTGT-L8TX_201105_01_A01 Isocortex-1 ACA
    class_label subclass_label
211 IT-ET Glut  L2 IT PPP-APr Glut
289 IT-ET Glut  L2 IT PPP-APr Glut
316 IT-ET Glut  L2 IT PPP-APr Glut
376 IT-ET Glut  L2 IT PPP-APr Glut
397 IT-ET Glut  L2 IT PPP-APr Glut
456 IT-ET Glut  L5 IT CTX Glut

[1] 737230      6

In [45]:
count_subclass <- zeng_v3_metadata_filter %>%
  group_by(subclass_label) %>%
  summarise(count = n())
count_subclass

    subclass_label               count
1   ABC NN                         339
2   ACB-BST-FS D1 Gaba             315
3   ADP-MPO Trp73 Glut               3
4   AHN-RCH-LHA Otp Fezf1 Glut       2
5   AHN-SBPV-PVHd Pdrm12 Gaba        4
6   ARH-PVp Tbx3 Gaba                3
7   ARH-PVp Tbx3 Glut                1
8   AVPV-MEPO-SFO Tbr1 Glut          3
9   Astro-NT NN                    556
10  Astro-OLF NN                  1466
11  Astro-TE NN                  86398
12  Astroependymal NN               42
13  BAM NN                        2567
14  BST-MPN Six3 Nrgn Gaba          16
15  BST-SI-AAA Six3 Slc22a3 Gaba     7
16  CA1-ProS Glut                12034
17  CA2-FC-IG Glut                 227
18  CA3 Glut                      3068
19  CEA-AAA-BST Six3 Sp9 Gaba      128
20  CEA-BST Ebf1 Pdyn Gaba          14
21  CEA-BST Rai14 Pdyn Crh Gaba      5
22  CEA-BST Six3 Cyp26b1 Gaba       23
23  CHOR NN                        124
24  CLA-EPd-CTX Car3 Glut         1718
25  COAa-PAA-MEA Barhl2 Glut       294
26  COAp Grxcr2 Glut               582
27  CT SUB Glut                     20
28  CU-ECU-SPVI Foxb1 Glut           1
29  DC NN                          111
30  DG Glut                      12486
⋮   ⋮                            ⋮
121 Pineal Crx Glut                 19
122 Pvalb Gaba                    7656
123 Pvalb chandelier Gaba          699
124 RHP-COA Ndnf Gaba             1234
125 SBPV-PVa Six6 Satb2 Gaba         1
126 SCH Six6 Cdc14a Gaba             2
127 SCsg Gabrr2 Gaba                 9
128 SI-MA-ACB Ebf1 Bnc2 Gaba        45
129 SI-MA-LPO-LHA Skor1 Glut       117
130 SI-MPO-LPO Lhx8 Gaba            16
131 SMC NN                        4248
132 SNc-VTA-RAmb Foxa1 Dopa          1
133 STN-PSTN Pitx2 Glut              1
134 STR D1 Gaba                  29150
135 STR D1 Sema5a Gaba            3568
136 STR D2 Gaba                  29402
137 STR Lhx8 Gaba                  504
138 STR Prox1 Lhx6 Gaba            814
139 STR-PAL Chst9 Gaba            1924
140 SUB-ProS Glut                  246
141 Sncg Gaba                     3273
142 Sst Chodl Gaba                1097
143 Sst Gaba                     12193
144 TMd-DMH Foxd2 Gaba               4
145 TMv-PMv Tbx3 Hist-Gaba           1
146 TU-ARH Otp Six6 Gaba             2
147 Tanycyte NN                      3
148 VLMC NN                       3123
149 VMH Nr5a1 Glut                   4
150 Vip Gaba                     13427

In [46]:
count_subclass[count_subclass$count > 100,]
count_subclass[count_subclass$count > 100,]$subclass_label
count_subclass[count_subclass$count > 100,]$subclass_label -> subclass_100

   subclass_label            count
1  ABC NN                      339
2  ACB-BST-FS D1 Gaba          315
3  Astro-NT NN                 556
4  Astro-OLF NN               1466
5  Astro-TE NN               86398
6  BAM NN                     2567
7  CA1-ProS Glut             12034
8  CA2-FC-IG Glut              227
9  CA3 Glut                   3068
10 CEA-AAA-BST Six3 Sp9 Gaba   128
11 CHOR NN                     124
12 CLA-EPd-CTX Car3 Glut      1718
13 COAa-PAA-MEA Barhl2 Glut    294
14 COAp Grxcr2 Glut            582
15 DC NN                       111
16 DG Glut                   12486
17 DG-PIR Ex IMN              1369
18 Endo NN                   29303
19 Ependymal NN                101
20 HPF CR Glut                 681
21 IA Mgp Gaba                 112
22 IT AON-TT-DP Glut          3383
23 IT EP-CLA Glut             2315
24 L2/3 IT CTX Glut          49186
25 L2/3 IT ENT Glut            109
26 L2/3 IT PIR-ENTl Glut      7215
27 L2/3 IT RSP Glut           8196
28 L4 RSP-ACA Glut            1563
29 L4/5 IT CTX Glut          82909
30 L5 ET CTX Glut             5988
⋮  ⋮                         ⋮
47 OB Eomes Ms4a15 Glut        755
48 OB Meis2 Thsd7b Gaba       1331
49 OB Trdn Gaba               2203
50 OB-STR-CTX Inh IMN         6875
51 OB-in Frmd7 Gaba          33020
52 OB-mi Frmd7 Gaba            375
53 OB-out Frmd7 Gaba          4385
54 OEC NN                      688
55 OPC NN                    28260
56 OT D3 Folh1 Gaba           7739
57 Oligo NN                  47325
58 PAL-STR Gaba-Chol           109
59 Peri NN                    7564
60 Pvalb Gaba                 7656
61 Pvalb chandelier Gaba       699
62 RHP-COA Ndnf Gaba          1234
63 SI-MA-LPO-LHA Skor1 Glut    117
64 SMC NN                     4248
65 STR D1 Gaba               29150
66 STR D1 Sema5a Gaba         3568
67 STR D2 Gaba               29402
68 STR Lhx8 Gaba               504
69 STR Prox1 Lhx6 Gaba         814
70 STR-PAL Chst9 Gaba         1924
71 SUB-ProS Glut               246
72 Sncg Gaba                  3273
73 Sst Chodl Gaba             1097
74 Sst Gaba                  12193
75 VLMC NN                    3123
76 Vip Gaba                  13427

 [1] "ABC NN"                    "ACB-BST-FS D1 Gaba"
 [3] "Astro-NT NN"               "Astro-OLF NN"
 [5] "Astro-TE NN"               "BAM NN"
 [7] "CA1-ProS Glut"             "CA2-FC-IG Glut"
 [9] "CA3 Glut"                  "CEA-AAA-BST Six3 Sp9 Gaba"
[11] "CHOR NN"                   "CLA-EPd-CTX Car3 Glut"
[13] "COAa-PAA-MEA Barhl2 Glut"  "COAp Grxcr2 Glut"
[15] "DC NN"                     "DG Glut"
[17] "DG-PIR Ex IMN"             "Endo NN"
[19] "Ependymal NN"              "HPF CR Glut"
[21] "IA Mgp Gaba"               "IT AON-TT-DP Glut"
[23] "IT EP-CLA Glut"            "L2/3 IT CTX Glut"
[25] "L2/3 IT ENT Glut"          "L2/3 IT PIR-ENTl Glut"
[27] "L2/3 IT RSP Glut"          "L4 RSP-ACA Glut"
[29] "L4/5 IT CTX Glut"          "L5 ET CTX Glut"
[31] "L5 IT CTX Glut"            "L5 NP CTX Glut"
[33] "L5/6 IT TPE-ENT Glut"      "L6 CT CTX Glut"
[35] "L6 IT CTX Glut"            "L6b CTX Glut"
[37] "L6b EPd Glut"              "LA-BLA-BMA-PA Glut"
[39] "Lamp5 Gaba"                "Lamp5 Lhx6 Gaba"
[41] "Lymphoid NN"               "MEA Slc17a7 Glut"
[43] "MEA-BST Sox6 Gaba"         "Microglia NN"
[45] "NDB-SI-ant Prdm12 Gaba"    "OB Dopa-Gaba"
[47] "OB Eomes Ms4a15 Glut"      "OB Meis2 Thsd7b Gaba"
[49] "OB Trdn Gaba"              "OB-STR-CTX Inh IMN"
[51] "OB-in Frmd7 Gaba"          "OB-mi Frmd7 Gaba"
[53] "OB-out Frmd7 Gaba"         "OEC NN"
[55] "OPC NN"                    "OT D3 Folh1 Gaba"
[57] "Oligo NN"                  "PAL-STR Gaba-Chol"
[59] "Peri NN"                   "Pvalb Gaba"
[61] "Pvalb chandelier Gaba"     "RHP-COA Ndnf Gaba"
[63] "SI-MA-LPO-LHA Skor1 Glut"  "SMC NN"
[65] "STR D1 Gaba"               "STR D1 Sema5a Gaba"
[67] "STR D2 Gaba"               "STR Lhx8 Gaba"
[69] "STR Prox1 Lhx6 Gaba"       "STR-PAL Chst9 Gaba"
[71] "SUB-ProS Glut"             "Sncg Gaba"
[73] "Sst Chodl Gaba"            "Sst Gaba"
[75] "VLMC NN"                   "Vip Gaba"

In [47]:
zeng_v3_metadata_filter2 <- zeng_v3_metadata_filter[zeng_v3_metadata_filter$subclass_label %in% subclass_100,]
head(zeng_v3_metadata_filter2);dim(zeng_v3_metadata_filter2)

    cluster_alias cell_new                            region      region_label
456 100           TGCAGATCATCAGTGT-L8TX_201105_01_A01 Isocortex-1 ACA
457 100           TGCATGAGTAGTCGGA-L8TX_201015_01_C03 Isocortex-1 PL-ILA-ORB
458 100           GTCCCATGTCTCGCGA-L8TX_201030_01_F11 Isocortex-1 ACA
459 100           TTTCACAGTCAGTTTG-L8TX_201105_01_A01 Isocortex-1 ACA
460 100           TGGATGTGTGGCACTC-L8TX_201105_01_A01 Isocortex-1 ACA
461 100           TACGGGCTCGGTAGGA-L8TX_201016_01_C04 Isocortex-1 ACA
    class_label subclass_label
456 IT-ET Glut  L5 IT CTX Glut
457 IT-ET Glut  L5 IT CTX Glut
458 IT-ET Glut  L5 IT CTX Glut
459 IT-ET Glut  L5 IT CTX Glut
460 IT-ET Glut  L5 IT CTX Glut
461 IT-ET Glut  L5 IT CTX Glut

[1] 736341      6

In [48]:
set.seed(20240812)

In [49]:
random_sample_1000 <- zeng_v3_metadata_filter2 %>%
  group_by(region_label, class_label, subclass_label) %>%
  slice_sample(n = 1000)

In [50]:
head(random_sample_1000);dim(random_sample_1000)

  cluster_alias cell_new                            region      region_label
1 14939         ACCTACCTCAGGAGAC-L8TX_201016_01_G04 Isocortex-2 ACA
2 14939         CCTACGTAGACTTCCA-L8TX_200903_01_F11 Isocortex-2 ACA
3 14939         GACACGCGTGTCGATT-L8TX_201105_01_A01 Isocortex-2 ACA
4 14939         GCGTGCAGTAGTTCCA-L8TX_200903_01_E01 Isocortex-1 ACA
5 14939         TTGCGTCAGCGACATG-L8TX_201030_01_F11 Isocortex-2 ACA
6 14939         TGGAGAGTCGCTTACC-L8TX_201016_01_D04 Isocortex-1 ACA
  class_label subclass_label
1 Astro-Epen  Astro-TE NN
2 Astro-Epen  Astro-TE NN
3 Astro-Epen  Astro-TE NN
4 Astro-Epen  Astro-TE NN
5 Astro-Epen  Astro-TE NN
6 Astro-Epen  Astro-TE NN

[1] 229669      6

In [51]:
length(unique(random_sample_1000$subclass_label))

[1] 76

In [52]:
unique(random_sample_1000$subclass_label)

 [1] "Astro-TE NN"               "OT D3 Folh1 Gaba"
 [3] "STR D1 Gaba"               "STR D2 Gaba"
 [5] "STR-PAL Chst9 Gaba"        "Sst Chodl Gaba"
 [7] "Lamp5 Gaba"                "RHP-COA Ndnf Gaba"
 [9] "Sncg Gaba"                 "Vip Gaba"
[11] "Lamp5 Lhx6 Gaba"           "Pvalb Gaba"
[13] "Pvalb chandelier Gaba"     "Sst Gaba"
[15] "CA2-FC-IG Glut"            "IT AON-TT-DP Glut"
[17] "IT EP-CLA Glut"            "L2/3 IT CTX Glut"
[19] "L2/3 IT RSP Glut"          "L4 RSP-ACA Glut"
[21] "L4/5 IT CTX Glut"          "L5 ET CTX Glut"
[23] "L5 IT CTX Glut"            "L5/6 IT TPE-ENT Glut"
[25] "L6 IT CTX Glut"            "BAM NN"
[27] "DC NN"                     "Lymphoid NN"
[29] "Microglia NN"              "L5 NP CTX Glut"
[31] "L6 CT CTX Glut"            "L6b CTX Glut"
[33] "HPF CR Glut"               "OB Dopa-Gaba"
[35] "OB-in Frmd7 Gaba"          "OB-out Frmd7 Gaba"
[37] "OPC NN"                    "Oligo NN"
[39] "ABC NN"                    "Endo NN"
[41] "Peri NN"                   "SMC NN"
[43] "VLMC NN"                   "Astro-NT NN"
[45] "CEA-AAA-BST Six3 Sp9 Gaba" "COAa-PAA-MEA Barhl2 Glut"
[47] "IA Mgp Gaba"               "STR D1 Sema5a Gaba"
[49] "STR Prox1 Lhx6 Gaba"       "DG-PIR Ex IMN"
[51] "CLA-EPd-CTX Car3 Glut"     "L2/3 IT ENT Glut"
[53] "L2/3 IT PIR-ENTl Glut"     "L6b EPd Glut"
[55] "OB-mi Frmd7 Gaba"          "Ependymal NN"
[57] "LA-BLA-BMA-PA Glut"        "OB Meis2 Thsd7b Gaba"
[59] "OB-STR-CTX Inh IMN"        "CHOR NN"
[61] "MEA-BST Sox6 Gaba"         "DG Glut"
[63] "CA1-ProS Glut"             "CA3 Glut"
[65] "SUB-ProS Glut"             "Astro-OLF NN"
[67] "OB Eomes Ms4a15 Glut"      "OB Trdn Gaba"
[69] "OEC NN"                    "ACB-BST-FS D1 Gaba"
[71] "NDB-SI-ant Prdm12 Gaba"    "SI-MA-LPO-LHA Skor1 Glut"
[73] "PAL-STR Gaba-Chol"         "COAp Grxcr2 Glut"
[75] "MEA Slc17a7 Glut"          "STR Lhx8 Gaba"

In [53]:
grep("Astro",unique(random_sample_1000$subclass_label),value = T)

[1] "Astro-TE NN"  "Astro-NT NN"  "Astro-OLF NN"

In [ ]:
saveRDS(random_sample_1000,sprintf("%s/01-zeng_v3_metadata_downsample_1000.rds",outdir))