In [17]:
import pandas as pd
import numpy as np

In [ ]:
# "indir" is a custom input path, and "outdir" is a custom output path.
# indir=""
# outdir=""

In [ ]:
cor_df=pd.read_csv("../../input/01-youth/correspondence_of_subclass_and_class_for_integration_with_zeng.csv")

In [19]:
cor_df

                 subclass           class
0        L2/3 IT CTX Glut      IT-ET Glut
1        L4/5 IT CTX Glut      IT-ET Glut
2          L5 IT CTX Glut      IT-ET Glut
3        L2/3 IT RSP Glut      IT-ET Glut
4         L4 RSP-ACA Glut      IT-ET Glut
5          L5 ET CTX Glut      IT-ET Glut
6           SUB-ProS Glut      IT-ET Glut
7           CA1-ProS Glut      IT-ET Glut
8                CA3 Glut      IT-ET Glut
9   CLA-EPd-CTX Car3 Glut      IT-ET Glut
10         L5 NP CTX Glut  NP-CT-L6b Glut
11         L6 CT CTX Glut  NP-CT-L6b Glut
12                DG Glut     DG-IMN Glut
13   OB Eomes Ms4a15 Glut      OB-CR Glut
14       OB-in Frmd7 Gaba     OB-IMN GABA
15      OB-out Frmd7 Gaba     OB-IMN GABA
16           OB Dopa-Gaba     OB-IMN GABA
17     OB-STR-CTX Inh IMN     OB-IMN GABA
18              Sncg Gaba    CTX-CGE GABA
19             Lamp5 Gaba    CTX-CGE GABA
20             Pvalb Gaba    CTX-MGE GABA
21               Sst Gaba    CTX-MGE GABA
22            STR D1 Gaba    CNU-LGE GABA
23            STR D2 Gaba    CNU-LGE GABA
24     ACB-BST-FS D1 Gaba    CNU-HYa GABA
25            Astro-TE NN      Astro-Epen
26               Oligo NN       OPC-Oligo
27                 OPC NN       OPC-Oligo
28                 OEC NN             OEC
29           Microglia NN          Immune

In [20]:
def get_threeclass(class_name):
    class_suffix=class_name.split()[-1]
    if class_suffix in ["GABA", "Glut"]:
        return class_suffix
    else:
        return "non"

In [21]:
cor_df["threeclass"]=cor_df["class"].apply(get_threeclass)

In [22]:
cor_df

                 subclass           class threeclass
0        L2/3 IT CTX Glut      IT-ET Glut       Glut
1        L4/5 IT CTX Glut      IT-ET Glut       Glut
2          L5 IT CTX Glut      IT-ET Glut       Glut
3        L2/3 IT RSP Glut      IT-ET Glut       Glut
4         L4 RSP-ACA Glut      IT-ET Glut       Glut
5          L5 ET CTX Glut      IT-ET Glut       Glut
6           SUB-ProS Glut      IT-ET Glut       Glut
7           CA1-ProS Glut      IT-ET Glut       Glut
8                CA3 Glut      IT-ET Glut       Glut
9   CLA-EPd-CTX Car3 Glut      IT-ET Glut       Glut
10         L5 NP CTX Glut  NP-CT-L6b Glut       Glut
11         L6 CT CTX Glut  NP-CT-L6b Glut       Glut
12                DG Glut     DG-IMN Glut       Glut
13   OB Eomes Ms4a15 Glut      OB-CR Glut       Glut
14       OB-in Frmd7 Gaba     OB-IMN GABA       GABA
15      OB-out Frmd7 Gaba     OB-IMN GABA       GABA
16           OB Dopa-Gaba     OB-IMN GABA       GABA
17     OB-STR-CTX Inh IMN     OB-IMN GABA       GABA
18              Sncg Gaba    CTX-CGE GABA       GABA
19             Lamp5 Gaba    CTX-CGE GABA       GABA
20             Pvalb Gaba    CTX-MGE GABA       GABA
21               Sst Gaba    CTX-MGE GABA       GABA
22            STR D1 Gaba    CNU-LGE GABA       GABA
23            STR D2 Gaba    CNU-LGE GABA       GABA
24     ACB-BST-FS D1 Gaba    CNU-HYa GABA       GABA
25            Astro-TE NN      Astro-Epen        non
26               Oligo NN       OPC-Oligo        non
27                 OPC NN       OPC-Oligo        non
28                 OEC NN             OEC        non
29           Microglia NN          Immune        non

In [23]:
from collections import Counter
Counter(cor_df["class"])

Counter({'IT-ET Glut': 10,
         'OB-IMN GABA': 4,
         'NP-CT-L6b Glut': 2,
         'CTX-CGE GABA': 2,
         'CTX-MGE GABA': 2,
         'CNU-LGE GABA': 2,
         'OPC-Oligo': 2,
         'DG-IMN Glut': 1,
         'OB-CR Glut': 1,
         'CNU-HYa GABA': 1,
         'Astro-Epen': 1,
         'OEC': 1,
         'Immune': 1})

In [24]:
Counter(cor_df["threeclass"])

Counter({'Glut': 14, 'GABA': 11, 'non': 5})

In [ ]:
#clear the files
for i in cor_df.iterrows():
    subclass_=i[1]["subclass"]
    class_=i[1]["class"]
    threeclass_=i[1]["threeclass"]
    with open(f"{indir}/5mC_"+class_.replace(" ",".").replace("/",".")+".txt","wt") as f:
        f.write("")
    with open(f"{indir}/5hmC_"+class_.replace(" ",".").replace("/",".")+".txt","wt") as f:
        f.write("")
    with open(f"{indir}/5mC_"+threeclass_.replace(" ",".").replace("/",".")+".txt","wt") as f:
        f.write("")
    with open(f"{indir}/5hmC_"+threeclass_.replace(" ",".").replace("/",".")+".txt","wt") as f:
        f.write("")

In [ ]:
for i in cor_df.iterrows():
    subclass_=i[1]["subclass"]
    class_=i[1]["class"]
    threeclass_=i[1]["threeclass"]

    with open(f"{indir}/5mC_"+class_.replace(" ",".").replace("/",".")+".txt","at") as f:
        f.write(f"{outdir}/5mC_"+subclass_.replace(" ",".").replace("/",".")+".Merge.allc.tsv.gz\n")
    
    with open(f"{indir}/5hmC_"+class_.replace(" ",".").replace("/",".")+".txt","at") as f:
        f.write(f"{outdir}/5hmC_"+subclass_.replace(" ",".").replace("/",".")+".Merge.allc.tsv.gz\n")
    
    with open(f"{indir}/5mC_"+threeclass_.replace(" ",".").replace("/",".")+".txt","at") as f:
        f.write(f"{outdir}/5mC_"+subclass_.replace(" ",".").replace("/",".")+".Merge.allc.tsv.gz\n")
    
    with open(f"{indir}/5hmC_"+threeclass_.replace(" ",".").replace("/",".")+".txt","at") as f:
        f.write(f"{outdir}/5hmC_"+subclass_.replace(" ",".").replace("/",".")+".Merge.allc.tsv.gz\n")