In [1]:
library(dplyr)

Warning message:
“package ‘dplyr’ was built under R version 4.3.2”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:
file_list <- list.files(path = "./", 
                        pattern = "\\.mcool$", full.names = FALSE)
head(file_list);length(file_list)

[1] "ABC_NN.Q.100K.mcool"
[2] "ACB-BST-FS_D1_Gaba.Q.100K.mcool"
[3] "AD_Serpinb7_Glut.Q.100K.mcool"
[4] "ADP-MPO_Trp73_Glut.Q.100K.mcool"
[5] "AHN_Onecut3_Gaba.Q.100K.mcool"
[6] "AHN-RCH-LHA_Otp_Fezf1_Glut.Q.100K.mcool"

[1] 273

In [3]:
subclass_v1 <- sub("\\.Q\\.100K\\.mcool$", "", file_list) %>% data.frame()
colnames(subclass_v1) <- "subclass_v1"
head(subclass_v1);dim(subclass_v1)

  subclass_v1
1 ABC_NN
2 ACB-BST-FS_D1_Gaba
3 AD_Serpinb7_Glut
4 ADP-MPO_Trp73_Glut
5 AHN_Onecut3_Gaba
6 AHN-RCH-LHA_Otp_Fezf1_Glut

[1] 273   1

In [4]:
subclass_v1

    subclass_v1
1   ABC_NN
2   ACB-BST-FS_D1_Gaba
3   AD_Serpinb7_Glut
4   ADP-MPO_Trp73_Glut
5   AHN_Onecut3_Gaba
6   AHN-RCH-LHA_Otp_Fezf1_Glut
7   AHN-SBPV-PVHd_Pdrm12_Gaba
8   APN_C1ql2_Glut
9   APN_C1ql4_Glut
10  ARH-PVp_Tbx3_Gaba
11  ARH-PVp_Tbx3_Glut
12  Astro-NT_NN
13  Astro-TE_NN
14  AV_Col27a1_Glut
15  AVPV-MEPO-SFO_Tbr1_Glut
16  B-PB_Nr4a2_Glut
17  Bergmann_NN
18  BST_Tac2_Gaba
19  BST-MPN_Six3_Nrgn_Gaba
20  BST-po_Iigp1_Glut
21  BST-SI-AAA_Six3_Slc22a3_Gaba
22  CA1-ProS_Glut
23  CA2-FC-IG_Glut
24  CA3_Glut
25  CB_Granule_Glut
26  CB_PLI_Gly-Gaba
27  CBN_Neurod2_Pvalb_Glut
28  CBX_Golgi_Gly-Gaba
29  CBX_MLI_Cdh22_Gaba
30  CBX_MLI_Megf11_Gaba
⋮   ⋮
244 SNc-VTA-RAmb_Foxa1_Dopa
245 Sncg_Gaba
246 SNr_Six3_Gaba
247 SNr-VTA_Pax5_Npas1_Gaba
248 SPA-SPFm-SPFp-POL-PIL-PoT_Sp9_Glut
249 SPVC_Mafa_Glut
250 SPVI-SPVC_Sall3_Lhx1_Gly-Gaba
251 SPVI-SPVC_Sall3_Nfib_Gly-Gaba
252 SPVI-SPVC_Tlx3_Ebf3_Glut
253 SPVO_Mafa_Meis2_Glut
254 Sst_Chodl_Gaba
255 Sst_Gaba
256 STN-PSTN_Pitx2_Glut
257 STR_D1_Gaba
258 STR_D1_Sema5a_Gaba
259 STR_D2_Gaba
260 STR_Lhx8_Gaba
261 STR_Prox1_Lhx6_Gaba
262 STR-PAL_Chst9_Gaba
263 SUB-ProS_Glut
264 TH_Prkcd_Grin2c_Glut
265 TMv-PMv_Tbx3_Hist-Gaba
266 TRS-BAC_Sln_Glut
267 TU-ARH_Otp_Six6_Gaba
268 VCO_Mafa_Meis2_Glut
269 Vip_Gaba
270 VLMC_NN
271 VMH_Fezf1_Glut
272 VMH_Nr5a1_Glut
273 ZI_Pax6_Gaba

In [5]:
library(Seurat)

Warning message:
“package ‘Seurat’ was built under R version 4.3.3”
Loading required package: SeuratObject

Warning message:
“package ‘SeuratObject’ was built under R version 4.3.3”
Loading required package: sp

Warning message:
“package ‘sp’ was built under R version 4.3.2”

Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, t

In [ ]:
subclass_label <- readRDS("../../../03.data/04.config_files/subclass_order.of_Joint_Cabernet.rds") %>% data.frame()
colnames(subclass_label) <- "V1"
subclass_label

   V1
1  L2/3 IT CTX Glut
2  L4/5 IT CTX Glut
3  L5 IT CTX Glut
4  L6 IT CTX Glut
5  IT AON-TT-DP Glut
6  LA-BLA-BMA-PA Glut
7  L2/3 IT RSP Glut
8  L4 RSP-ACA Glut
9  L5 ET CTX Glut
10 SUB-ProS Glut
11 CA1-ProS Glut
12 CA3 Glut
13 CLA-EPd-CTX Car3 Glut
14 L5 NP CTX Glut
15 L6 CT CTX Glut
16 DG Glut
17 OB Eomes Ms4a15 Glut
18 OB-in Frmd7 Gaba
19 OB-out Frmd7 Gaba
20 Sncg Gaba
21 Lamp5 Gaba
22 Pvalb Gaba
23 Sst Gaba
24 STR D1 Gaba
25 STR D2 Gaba
26 ACB-BST-FS D1 Gaba
27 Astro-TE NN
28 Oligo NN
29 OPC NN
30 OEC NN
31 Microglia NN

In [7]:
unique(subclass_label$V1)

 [1] "L2/3 IT CTX Glut"      "L4/5 IT CTX Glut"      "L5 IT CTX Glut"
 [4] "L6 IT CTX Glut"        "IT AON-TT-DP Glut"     "LA-BLA-BMA-PA Glut"
 [7] "L2/3 IT RSP Glut"      "L4 RSP-ACA Glut"       "L5 ET CTX Glut"
[10] "SUB-ProS Glut"         "CA1-ProS Glut"         "CA3 Glut"
[13] "CLA-EPd-CTX Car3 Glut" "L5 NP CTX Glut"        "L6 CT CTX Glut"
[16] "DG Glut"               "OB Eomes Ms4a15 Glut"  "OB-in Frmd7 Gaba"
[19] "OB-out Frmd7 Gaba"     "Sncg Gaba"             "Lamp5 Gaba"
[22] "Pvalb Gaba"            "Sst Gaba"              "STR D1 Gaba"
[25] "STR D2 Gaba"           "ACB-BST-FS D1 Gaba"    "Astro-TE NN"
[28] "Oligo NN"              "OPC NN"                "OEC NN"
[31] "Microglia NN"

In [8]:
grep("CTX",subclass_v1$subclass_v1,value = T)

 [1] "CLA-EPd-CTX_Car3_Glut" "L2_3_IT_CTX_Glut"      "L4_5_IT_CTX_Glut"
 [4] "L5_ET_CTX_Glut"        "L5_IT_CTX_Glut"        "L5_NP_CTX_Glut"
 [7] "L6_CT_CTX_Glut"        "L6_IT_CTX_Glut"        "L6b_CTX_Glut"
[10] "OB-STR-CTX_Inh_IMN"

In [9]:
grep("RSP",subclass_v1$subclass_v1,value = T)

[1] "L2_3_IT_RSP_Glut" "L4_RSP-ACA_Glut"

In [10]:
grep("ProS",subclass_v1$subclass_v1,value = T)

[1] "CA1-ProS_Glut" "SUB-ProS_Glut"

In [11]:
grep("CA3",subclass_v1$subclass_v1,value = T)

[1] "CA3_Glut"

In [12]:
grep("DG",subclass_v1$subclass_v1,value = T)

[1] "DG_Glut"       "DG-PIR_Ex_IMN"

In [13]:
grep("OB",subclass_v1$subclass_v1,value = T)

[1] "OB_Dopa-Gaba"         "OB_Eomes_Ms4a15_Glut" "OB_Trdn_Gaba"
[4] "OB-in_Frmd7_Gaba"     "OB-out_Frmd7_Gaba"    "OB-STR-CTX_Inh_IMN"

In [14]:
grep("Sncg",subclass_v1$subclass_v1,value = T)

[1] "Sncg_Gaba"

In [15]:
grep("Lamp5",subclass_v1$subclass_v1,value = T)

[1] "Lamp5_Gaba"      "Lamp5_Lhx6_Gaba"

In [16]:
grep("Pvalb",subclass_v1$subclass_v1,value = T)

[1] "CBN_Neurod2_Pvalb_Glut" "PSV_Pvalb_Lhx2_Glut"    "Pvalb_chandelier_Gaba"
[4] "Pvalb_Gaba"

In [17]:
grep("Sst",subclass_v1$subclass_v1,value = T)

[1] "Sst_Chodl_Gaba" "Sst_Gaba"

In [18]:
grep("STR",subclass_v1$subclass_v1,value = T)

[1] "NDB-SI-MA-STRv_Lhx8_Gaba" "OB-STR-CTX_Inh_IMN"
[3] "PAL-STR_Gaba-Chol"        "STR_D1_Gaba"
[5] "STR_D1_Sema5a_Gaba"       "STR_D2_Gaba"
[7] "STR_Lhx8_Gaba"            "STR_Prox1_Lhx6_Gaba"
[9] "STR-PAL_Chst9_Gaba"

In [19]:
grep("ACB",subclass_v1$subclass_v1,value = T)

[1] "ACB-BST-FS_D1_Gaba"       "SI-MA-ACB_Ebf1_Bnc2_Gaba"

In [20]:
grep("Astro",subclass_v1$subclass_v1,value = T)

[1] "Astro-NT_NN" "Astro-TE_NN"

In [21]:
grep("Oligo",subclass_v1$subclass_v1,value = T)

[1] "Oligo_NN"

In [22]:
grep("OPC",subclass_v1$subclass_v1,value = T)

[1] "OPC_NN"

In [23]:
grep("OEC",subclass_v1$subclass_v1,value = T)

character(0)

In [24]:
grep("Microglia",subclass_v1$subclass_v1,value = T)

[1] "Microglia_NN"

In [25]:
grep("NN",subclass_v1$subclass_v1,value = T)

 [1] "ABC_NN"       "Astro-NT_NN"  "Astro-TE_NN"  "Bergmann_NN"  "CHOR_NN"
 [6] "Endo_NN"      "Microglia_NN" "Oligo_NN"     "OPC_NN"       "Peri_NN"
[11] "VLMC_NN"

In [26]:
grep("IT",subclass_v1$subclass_v1,value = T)

 [1] "IT_AON-TT-DP_Glut"     "IT_EP-CLA_Glut"        "L2_3_IT_CTX_Glut"
 [4] "L2_3_IT_ENT_Glut"      "L2_3_IT_PIR-ENTl_Glut" "L2_3_IT_PPP_Glut"
 [7] "L2_3_IT_RSP_Glut"      "L2_IT_ENT-po_Glut"     "L2_IT_PPP-APr_Glut"
[10] "L4_5_IT_CTX_Glut"      "L5_6_IT_TPE-ENT_Glut"  "L5_IT_CTX_Glut"
[13] "L6_IT_CTX_Glut"

In [27]:
grep("LA",subclass_v1$subclass_v1,value = T)

[1] "CLA-EPd-CTX_Car3_Glut" "IT_EP-CLA_Glut"        "LA-BLA-BMA-PA_Glut"

In [28]:
subclass_final <- data.frame(subclass_our=c('L2/3 IT CTX Glut','L4/5 IT CTX Glut','L5 IT CTX Glut','L6 IT CTX Glut','IT AON-TT-DP Glut',
                                            'LA-BLA-BMA-PA Glut','L2/3 IT RSP Glut','L4 RSP-ACA Glut','L5 ET CTX Glut','SUB-ProS Glut',
                                            'CA1-ProS Glut','CA3 Glut','CLA-EPd-CTX Car3 Glut','L5 NP CTX Glut','L6 CT CTX Glut','DG Glut',
                                            'OB Eomes Ms4a15 Glut','OB-in Frmd7 Gaba','OB-out Frmd7 Gaba','Sncg Gaba','Lamp5 Gaba',
                                            'Pvalb Gaba','Sst Gaba','STR D1 Gaba','STR D2 Gaba','ACB-BST-FS D1 Gaba','Astro-TE NN',
                                            'Oligo NN','OPC NN','Microglia NN'),
                            subclass_liu=c('L2_3_IT_CTX_Glut','L4_5_IT_CTX_Glut','L5_IT_CTX_Glut','L6_IT_CTX_Glut','IT_AON-TT-DP_Glut',
                                            'LA-BLA-BMA-PA_Glut','L2_3_IT_RSP_Glut','L4_RSP-ACA_Glut','L5_ET_CTX_Glut','SUB-ProS_Glut',
                                            'CA1-ProS_Glut','CA3_Glut','CLA-EPd-CTX_Car3_Glut','L5_NP_CTX_Glut','L6_CT_CTX_Glut',
                                            'DG_Glut','OB_Eomes_Ms4a15_Glut','OB-in_Frmd7_Gaba','OB-out_Frmd7_Gaba','Sncg_Gaba','Lamp5_Gaba',
                                            'Pvalb_Gaba','Sst_Gaba','STR_D1_Gaba','STR_D2_Gaba','ACB-BST-FS_D1_Gaba','Astro-TE_NN','Oligo_NN',
                                            'OPC_NN','Microglia_NN'))

subclass_final

   subclass_our          subclass_liu
1  L2/3 IT CTX Glut      L2_3_IT_CTX_Glut
2  L4/5 IT CTX Glut      L4_5_IT_CTX_Glut
3  L5 IT CTX Glut        L5_IT_CTX_Glut
4  L6 IT CTX Glut        L6_IT_CTX_Glut
5  IT AON-TT-DP Glut     IT_AON-TT-DP_Glut
6  LA-BLA-BMA-PA Glut    LA-BLA-BMA-PA_Glut
7  L2/3 IT RSP Glut      L2_3_IT_RSP_Glut
8  L4 RSP-ACA Glut       L4_RSP-ACA_Glut
9  L5 ET CTX Glut        L5_ET_CTX_Glut
10 SUB-ProS Glut         SUB-ProS_Glut
11 CA1-ProS Glut         CA1-ProS_Glut
12 CA3 Glut              CA3_Glut
13 CLA-EPd-CTX Car3 Glut CLA-EPd-CTX_Car3_Glut
14 L5 NP CTX Glut        L5_NP_CTX_Glut
15 L6 CT CTX Glut        L6_CT_CTX_Glut
16 DG Glut               DG_Glut
17 OB Eomes Ms4a15 Glut  OB_Eomes_Ms4a15_Glut
18 OB-in Frmd7 Gaba      OB-in_Frmd7_Gaba
19 OB-out Frmd7 Gaba     OB-out_Frmd7_Gaba
20 Sncg Gaba             Sncg_Gaba
21 Lamp5 Gaba            Lamp5_Gaba
22 Pvalb Gaba            Pvalb_Gaba
23 Sst Gaba              Sst_Gaba
24 STR D1 Gaba           STR_D1_Gaba
25 STR D2 Gaba           STR_D2_Gaba
26 ACB-BST-FS D1 Gaba    ACB-BST-FS_D1_Gaba
27 Astro-TE NN           Astro-TE_NN
28 Oligo NN              Oligo_NN
29 OPC NN                OPC_NN
30 Microglia NN          Microglia_NN

In [29]:
table(subclass_final$subclass_liu %in% subclass_v1$subclass_v1)

TRUE
  30

In [30]:
table(subclass_final$subclass_our %in% subclass_label$V1)

TRUE
  30

In [ ]:
write.csv(subclass_final,"../../../03.data/02.metainfo/01.Young_Mouse/subclass_name.Joint_Cabernet_corresponding_to_3C.csv",row.names=F,quote=F)