In [1]:
import sys
import scanpy as sc
import pandas as pd
import numpy as np
from tqdm import tqdm

In [ ]:
adata_5hmCG = sc.read_h5ad("5hmC_chrom100k.CG.pass_total_QC.h5ad")

In [3]:
adata_5hmCG

AnnData object with n_obs × n_vars = 43075 × 24639
    obs: 'total_QC'
    var: 'chrom', 'end', 'start'

In [4]:
counts_5hmCG = adata_5hmCG.X
counts_5hmCG

array([[       nan,        nan,        nan, ..., 0.12195122, 0.23076923,
               nan],
       [       nan,        nan,        nan, ..., 0.06382979, 0.05970149,
               nan],
       [       nan,        nan,        nan, ..., 0.11428571, 0.07142857,
               nan],
       ...,
       [       nan,        nan,        nan, ..., 0.        , 0.28947368,
               nan],
       [       nan,        nan,        nan, ..., 0.10810811, 0.        ,
               nan],
       [       nan,        nan,        nan, ..., 0.09090909, 0.03571429,
               nan]], dtype=float32)

In [5]:
adata_5hmCG.obs

                                                    total_QC
cell
allc_P56_Male_DeepCortex_TSO_joint5hmC_plate92....         1
allc_P56_Male_DeepCortex_TSO_joint5hmC_plate92....         1
allc_P56_Male_DeepCortex_TSO_joint5hmC_plate92....         1
allc_P56_Male_DeepCortex_TSO_joint5hmC_plate92....         1
allc_P56_Male_DeepCortex_TSO_joint5hmC_plate92....         1
...                                                      ...
allc_P56_Male_SuperficialCortex_TSO_joint5hmC_p...         1
allc_P56_Male_SuperficialCortex_TSO_joint5hmC_p...         1
allc_P56_Male_SuperficialCortex_TSO_joint5hmC_p...         1
allc_P56_Male_SuperficialCortex_TSO_joint5hmC_p...         1
allc_P56_Male_SuperficialCortex_TSO_joint5hmC_p...         1

[43075 rows x 1 columns]

In [6]:
adata_5hmCG.obs.index = adata_5hmCG.obs.index.str.replace("allc_", "")
adata_5hmCG.obs

                                                    total_QC
cell
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAATCACC         1
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAATCCGT         1
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GACGAACT         1
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GACGTCAT         1
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAGAGTAC         1
...                                                      ...
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...         1
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...         1
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...         1
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...         1
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...         1

[43075 rows x 1 columns]

In [7]:
adata_5hmCG.var

          chrom        end      start
chrom100k
chr1_0     chr1     100000          0
chr1_1     chr1     200000     100000
chr1_2     chr1     300000     200000
chr1_3     chr1     400000     300000
chr1_4     chr1     500000     400000
...         ...        ...        ...
chr9_1241  chr9  124200000  124100000
chr9_1242  chr9  124300000  124200000
chr9_1243  chr9  124400000  124300000
chr9_1244  chr9  124500000  124400000
chr9_1245  chr9  124595110  124500000

[24639 rows x 3 columns]

In [8]:
counts_5hmCG = pd.DataFrame(counts_5hmCG, index=adata_5hmCG.obs.index, columns=adata_5hmCG.var.index)

In [9]:
counts_5hmCG

chrom100k,chr1_0,chr1_1,chr1_2,chr1_3,chr1_4,chr1_5,chr1_6,chr1_7,chr1_8,chr1_9,...,chr9_1236,chr9_1237,chr9_1238,chr9_1239,chr9_1240,chr9_1241,chr9_1242,chr9_1243,chr9_1244,chr9_1245
cell,,,,,,,,,,,,,,,,,,,,,
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAATCACC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.164835,0.173077,0.135135,0.112676,0.111111,0.066667,0.130435,0.121951,0.230769,NaN
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAATCCGT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.289474,0.255319,0.230769,0.097561,0.216216,0.277778,0.073171,0.063830,0.059701,NaN
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GACGAACT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.112903,0.049180,0.120690,0.051724,0.090909,0.133333,0.043478,0.114286,0.071429,NaN
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GACGTCAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.040541,0.019608,0.075000,0.035088,0.018868,0.000000,0.097561,0.000000,0.101266,NaN
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAGAGTAC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,0.250000,NaN,0.400000,0.058824,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P56_Male_SuperficialCortex_TSO_joint5hmC_plate60.AGTGACCT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.166667,0.350000,0.238095,0.288136,0.275000,0.240000,0.411765,0.190476,0.153846,NaN
P56_Male_SuperficialCortex_TSO_joint5hmC_plate60.ATAACGCC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.222222,0.162162,0.224490,0.172414,0.241379,0.266667,0.296296,0.058824,0.181818,NaN
P56_Male_SuperficialCortex_TSO_joint5hmC_plate60.ATCTGACC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.327273,0.223881,0.222222,0.131148,0.150000,0.307692,0.058824,0.000000,0.289474,NaN
P56_Male_SuperficialCortex_TSO_joint5hmC_plate60.CAACACAG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.250000,0.428571,0.300000,0.142857,0.160000,0.000000,0.375000,0.108108,0.000000,NaN
P56_Male_SuperficialCortex_TSO_joint5hmC_plate60.CAACTCCA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.117647,0.392857,0.125000,0.229167,0.156250,0.181818,0.136364,0.090909,0.035714,NaN

In [10]:
extracted_5hmCG = counts_5hmCG[['chr8_171']]

In [11]:
extracted_5hmCG

chrom100k                                           chr8_171
cell
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAATCACC  0.323077
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAATCCGT  0.208333
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GACGAACT  0.317073
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GACGTCAT  0.189189
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAGAGTAC       NaN
...                                                      ...
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.375000
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.400000
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.407407
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.300000
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.534483

[43075 rows x 1 columns]

In [12]:
total = len(extracted_5hmCG)
non_na = extracted_5hmCG['chr8_171'].notna().sum()
print(f"非NA数量: {non_na} / 总数: {total}（比例: {non_na / total:.3f}）")

非NA数量: 37845 / 总数: 43075（比例: 0.879）

In [13]:
extracted_5hmCG = counts_5hmCG[['chr7_903']]

In [14]:
extracted_5hmCG

chrom100k                                           chr7_903
cell
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAATCACC  0.224299
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAATCCGT  0.306818
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GACGAACT  0.237288
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GACGTCAT  0.311475
P56_Male_DeepCortex_TSO_joint5hmC_plate92.GAGAGTAC  0.000000
...                                                      ...
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.250000
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.370370
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.226415
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.440000
P56_Male_SuperficialCortex_TSO_joint5hmC_plate6...  0.288462

[43075 rows x 1 columns]

In [15]:
extracted_5hmCG.to_csv('../output/08-extracted_chr7_903_5hmCG.csv', index=True)

In [16]:
def extract_and_save_chromosome_column(adata_file_path, output_file_path, column_name):
    adata = sc.read_h5ad(adata_file_path)
    counts = adata.X
    adata.obs.index = adata.obs.index.str.replace("allc_", "")
    counts = pd.DataFrame(counts, index=adata.obs.index, columns=adata.var.index)
    extracted_data = counts[[column_name]]
    print(extracted_data.shape)
    extracted_data.to_csv(output_file_path, index=True)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr5_201_5hmCG.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr2_390_5hmCG.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_173_5hmCG.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_171_5hmCG.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_172_5hmCG.csv",
    column_name="chr8_172"
)

(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr7_903_5mCG.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr5_201_5mCG.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr2_390_5mCG.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_173_5mCG.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_171_5mCG.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_172_5mCG.csv",
    column_name="chr8_172"
)

(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr7_903_true5mCG.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr5_201_true5mCG.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr2_390_true5mCG.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_173_true5mCG.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_171_true5mCG.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CG.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_172_true5mCG.csv",
    column_name="chr8_172"
)

(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr7_903_5hmCH.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr5_201_5hmCH.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr2_390_5hmCH.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_173_5hmCH.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_171_5hmCH.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path="5hmC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_172_5hmCH.csv",
    column_name="chr8_172"
)

(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr7_903_5mCH.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr5_201_5mCH.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr2_390_5mCH.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_173_5mCH.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_171_5mCH.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path="5mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_172_5mCH.csv",
    column_name="chr8_172"
)

(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr7_903_true5mCH.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr5_201_true5mCH.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr2_390_true5mCH.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_173_true5mCH.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_171_true5mCH.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path="true_mC_chrom100k.CH.pass_total_QC.h5ad",
    output_file_path="../output/08-extracted_chr8_172_true5mCH.csv",
    column_name="chr8_172"
)

(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)
(43075, 1)