In [1]:
import sys
import scanpy as sc
import pandas as pd
import numpy as np
from tqdm import tqdm

In [ ]:
# "indir" is a custom input path, and "outdir" is a custom output path.
# indir=""
# outdir=""

In [ ]:
adata_5hmCG = sc.read_h5ad(f"{indir}/5hmC_chrom100k.CG.pass_paired_QC.h5ad")

In [3]:
adata_5hmCG

AnnData object with n_obs × n_vars = 44608 × 24639
    obs: 'SampleID', 'Plate_ID', 'Sample_ID_without_barcode', 'Unique_ID', 'Species', 'Datatype', 'Library', 'Region', 'Brain.Region', 'Batch', 'spatial_type', 'Age', 'Total_reads', 'Clean_reads', 'Filter_reads_r', 'Filter_base_r', 'raw_depth', 'clean_depth', 'Aligned_Reads', 'Align_rate', 'COVERAGE', 'chrM_readsN', 'Dup_rate', 'Mean_Insertion_size', 'Depth_after_align', 'lambda_aligned', 'fullpuc19_aligned', 'cla1_aligned', 'dna_CpG_Cov', 'dna_CGn', 'dna_mCG_R', 'dna_mCHG_R', 'dna_mCHH_R', 'fullpuc19_CGn_after', 'fullpuc19_mCG_R_after', 'lambda_CGn_after', 'lambda_mCG_R_after', 'cla1_CGn_after', 'cla1_mCG_R_after', 'dna_reads_num', 'rna_reads_num', 'dna_reads_ratio', 'rna_reads_ratio', 'dna_reads_coverage', 'rna_CpG_Cov', 'rna_CGn', 'rna_mCG_R', 'rna_mCHG_R', 'rna_mCHH_R', 'fullpuc19_CGn_pre', 'fullpuc19_mCG_R_pre', 'lambda_CGn_pre', 'lambda_mCG_R_pre', 'cla1_CGn_pre', 'cla1_mCG_R_pre', 'QC', 'class_label', 'subclass_label', 'three_class_label', 'Neuron_non_neuron', 'paired_QC'
    var: 'chrom', 'end', 'start'

In [4]:
counts_5hmCG = adata_5hmCG.X
counts_5hmCG

array([[       nan,        nan,        nan, ..., 0.1375    , 0.06190476,
               nan],
       [       nan,        nan,        nan, ..., 0.22222222, 0.07407407,
               nan],
       [       nan,        nan,        nan, ..., 0.08333334, 0.03846154,
               nan],
       ...,
       [       nan,        nan,        nan, ..., 0.04861111, 0.06060606,
               nan],
       [       nan,        nan,        nan, ..., 0.0952381 , 0.06      ,
               nan],
       [       nan,        nan,        nan, ..., 0.        , 0.5       ,
               nan]], dtype=float32)

In [5]:
adata_5hmCG.obs

,SampleID,Plate_ID,Sample_ID_without_barcode,Unique_ID,Species,Datatype,Library,Region,Brain.Region,Batch,...,lambda_CGn_pre,lambda_mCG_R_pre,cla1_CGn_pre,cla1_mCG_R_pre,QC,class_label,subclass_label,three_class_label,Neuron_non_neuron,paired_QC
cell,,,,,,,,,,,,,,,,,,,,,
allc_P56_Male_231127Mouse1_SuperficialCortex_EXP231130_TSO_joint5hmC_plate37.AACCAGAG,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_joint5hmC_plate37,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_plate37.AACCAGAG,mm10,TSO-joint-RNA,hmC,SuperficialCortex,Cortex,231226,...,224488,0.037900,5012.0,0.990400,1,IT-ET Glut,L2/3 IT CTX Glut,Exc,Neuron,1
allc_P56_Male_231127Mouse1_SuperficialCortex_EXP231130_TSO_joint5hmC_plate37.AAGACACC,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_joint5hmC_plate37,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_plate37.AAGACACC,mm10,TSO-joint-RNA,hmC,SuperficialCortex,Cortex,231226,...,160603,0.032200,5726.0,0.993500,1,IT-ET Glut,L2/3 IT CTX Glut,Exc,Neuron,1
allc_P56_Male_231127Mouse1_SuperficialCortex_EXP231130_TSO_joint5hmC_plate37.AAGACCGT,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_joint5hmC_plate37,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_plate37.AAGACCGT,mm10,TSO-joint-RNA,hmC,SuperficialCortex,Cortex,231226,...,282009,0.034300,6681.0,0.991800,1,CNU-HYa GABA,ACB-BST-FS D1 Gaba,Inh,Neuron,1
allc_P56_Male_231127Mouse1_SuperficialCortex_EXP231130_TSO_joint5hmC_plate37.AGACCTTG,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_joint5hmC_plate37,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_plate37.AGACCTTG,mm10,TSO-joint-RNA,hmC,SuperficialCortex,Cortex,231226,...,253075,0.031500,6369.0,0.988700,1,IT-ET Glut,L2/3 IT CTX Glut,Exc,Neuron,1
allc_P56_Male_231127Mouse1_SuperficialCortex_EXP231130_TSO_joint5hmC_plate37.AGACGCTA,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_joint5hmC_plate37,P56_Male_231127Mouse1_SuperficialCortex_EXP231...,P56_Male_SuperficialCortex_TSO_plate37.AGACGCTA,mm10,TSO-joint-RNA,hmC,SuperficialCortex,Cortex,231226,...,215283,0.025300,5884.0,0.993500,1,IT-ET Glut,L2/3 IT CTX Glut,Exc,Neuron,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
allc_P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_joint5hmC_plate10.GTCCTTGA,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_joint5hmC_plate10,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_plate10.GTCCTTGA,mm10,TSO-joint-RNA,hmC,LeftHippo,Hippo,240605,...,301141,0.012974,7003.0,0.996145,1,IT-ET Glut,CA3 Glut,Exc,Neuron,1
allc_P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_joint5hmC_plate10.TACTCCAG,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_joint5hmC_plate10,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_plate10.TACTCCAG,mm10,TSO-joint-RNA,hmC,LeftHippo,Hippo,240605,...,321823,0.010534,7143.0,0.997620,1,IT-ET Glut,CA1-ProS Glut,Exc,Neuron,1
allc_P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_joint5hmC_plate10.GGAGGAAT,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_joint5hmC_plate10,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_plate10.GGAGGAAT,mm10,TSO-joint-RNA,hmC,LeftHippo,Hippo,240605,...,625199,0.006756,2374.0,0.994524,1,DG-IMN Glut,DG Glut,Exc,Neuron,1
allc_P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_joint5hmC_plate10.GGTGTACA,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_joint5hmC_plate10,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_plate10.GGTGTACA,mm10,TSO-joint-RNA,hmC,LeftHippo,Hippo,240605,...,488689,0.018789,7222.0,0.995015,1,IT-ET Glut,CA1-ProS Glut,Exc,Neuron,1
allc_P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_joint5hmC_plate9.AGACGCTA,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_joint5hmC_plate9,P49_Male_240416Mouses_LeftHippo_EXP240426_TSO_...,P49_Male_LeftHippo_TSO_plate9.AGACGCTA,mm10,TSO-joint-RNA,hmC,LeftHippo,Hippo,240605,...,285886,0.012544,8287.0,0.996139,1,DG-IMN Glut,DG Glut,Exc,Neuron,1

In [6]:
adata_5hmCG.var

          chrom        end      start
chrom100k
chr1_0     chr1     100000          0
chr1_1     chr1     200000     100000
chr1_2     chr1     300000     200000
chr1_3     chr1     400000     300000
chr1_4     chr1     500000     400000
...         ...        ...        ...
chr9_1241  chr9  124200000  124100000
chr9_1242  chr9  124300000  124200000
chr9_1243  chr9  124400000  124300000
chr9_1244  chr9  124500000  124400000
chr9_1245  chr9  124595110  124500000

[24639 rows x 3 columns]

In [7]:
counts_5hmCG = pd.DataFrame(counts_5hmCG, index=adata_5hmCG.obs['Unique_ID'], columns=adata_5hmCG.var.index)

In [8]:
counts_5hmCG

chrom100k,chr1_0,chr1_1,chr1_2,chr1_3,chr1_4,chr1_5,chr1_6,chr1_7,chr1_8,chr1_9,...,chr9_1236,chr9_1237,chr9_1238,chr9_1239,chr9_1240,chr9_1241,chr9_1242,chr9_1243,chr9_1244,chr9_1245
Unique_ID,,,,,,,,,,,,,,,,,,,,,
P56_Male_SuperficialCortex_TSO_plate37.AACCAGAG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.138889,0.325000,0.105769,0.159420,0.115942,0.033333,0.125000,0.137500,0.061905,NaN
P56_Male_SuperficialCortex_TSO_plate37.AAGACACC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.122222,1.000000,0.000000,0.000000,0.272727,0.000000,0.000000,0.222222,0.074074,NaN
P56_Male_SuperficialCortex_TSO_plate37.AAGACCGT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.307692,0.109375,0.129032,0.220779,0.135135,0.228571,0.200000,0.083333,0.038462,NaN
P56_Male_SuperficialCortex_TSO_plate37.AGACCTTG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.212766,0.318182,0.262295,0.130435,0.191489,0.161290,0.257143,0.027778,0.047619,NaN
P56_Male_SuperficialCortex_TSO_plate37.AGACGCTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.228070,0.105263,0.272727,0.076923,0.230769,0.222222,0.117647,0.173913,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P49_Male_LeftHippo_TSO_plate10.GTCCTTGA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.185185,0.276596,0.257143,0.000000,0.000000,0.000000,0.166667,0.185185,0.000000,NaN
P49_Male_LeftHippo_TSO_plate10.TACTCCAG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.428571,0.073171,0.090909,0.103448,0.166667,0.090909,0.250000,0.000000,NaN,NaN
P49_Male_LeftHippo_TSO_plate10.GGAGGAAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.098039,0.117949,0.113402,0.058333,0.064815,0.062500,0.082192,0.048611,0.060606,NaN
P49_Male_LeftHippo_TSO_plate10.GGTGTACA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.191489,0.221154,0.272727,0.102041,0.111111,0.170213,0.200000,0.095238,0.060000,NaN
P49_Male_LeftHippo_TSO_plate9.AGACGCTA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.500000,NaN

In [9]:
extracted_5hmCG = counts_5hmCG[['chr7_903']]

In [10]:
extracted_5hmCG

chrom100k                                        chr7_903
Unique_ID
P56_Male_SuperficialCortex_TSO_plate37.AACCAGAG  0.207792
P56_Male_SuperficialCortex_TSO_plate37.AAGACACC       NaN
P56_Male_SuperficialCortex_TSO_plate37.AAGACCGT  0.146667
P56_Male_SuperficialCortex_TSO_plate37.AGACCTTG  0.298507
P56_Male_SuperficialCortex_TSO_plate37.AGACGCTA  0.310345
...                                                   ...
P49_Male_LeftHippo_TSO_plate10.GTCCTTGA          0.000000
P49_Male_LeftHippo_TSO_plate10.TACTCCAG          0.329114
P49_Male_LeftHippo_TSO_plate10.GGAGGAAT          0.500000
P49_Male_LeftHippo_TSO_plate10.GGTGTACA          0.181319
P49_Male_LeftHippo_TSO_plate9.AGACGCTA           0.000000

[44608 rows x 1 columns]

In [ ]:
extracted_5hmCG.to_csv(f'{outdir}/11-extracted_chr7_903_5hmCG.csv', index=True)

In [12]:
def extract_and_save_chromosome_column(adata_file_path, output_file_path, column_name):
    adata = sc.read_h5ad(adata_file_path)
    counts = adata.X
    counts = pd.DataFrame(counts, index=adata.obs['Unique_ID'], columns=adata.var.index)
    extracted_data = counts[[column_name]]
    print(extracted_data.shape)
    extracted_data.to_csv(output_file_path, index=True)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr5_201_5hmCG.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr2_390_5hmCG.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_173_5hmCG.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_171_5hmCG.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_172_5hmCG.csv",
    column_name="chr8_172"
)

(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr7_903_5mCG.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr5_201_5mCG.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr2_390_5mCG.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_173_5mCG.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_171_5mCG.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_172_5mCG.csv",
    column_name="chr8_172"
)

(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr7_903_true5mCG.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr5_201_true5mCG.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr2_390_true5mCG.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_173_true5mCG.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_171_true5mCG.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CG.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_172_true5mCG.csv",
    column_name="chr8_172"
)

(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr7_903_5hmCH.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr5_201_5hmCH.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr2_390_5hmCH.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_173_5hmCH.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_171_5hmCH.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5hmC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_172_5hmCH.csv",
    column_name="chr8_172"
)

(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr7_903_5mCH.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr5_201_5mCH.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr2_390_5mCH.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_173_5mCH.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_171_5mCH.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_172_5mCH.csv",
    column_name="chr8_172"
)

(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)

In [ ]:
extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr7_903_true5mCH.csv",
    column_name="chr7_903"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr5_201_true5mCH.csv",
    column_name="chr5_201"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr2_390_true5mCH.csv",
    column_name="chr2_390"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_173_true5mCH.csv",
    column_name="chr8_173"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_171_true5mCH.csv",
    column_name="chr8_171"
)

extract_and_save_chromosome_column(
    adata_file_path=f"{indir}/true_5mC_chrom100k.CH.pass_paired_QC.h5ad",
    output_file_path=f"{outdir}/11-extracted_chr8_172_true5mCH.csv",
    column_name="chr8_172"
)

(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)
(44608, 1)