In [1]:
library(Seurat)
library(dplyr)
library(tidyr)

Warning message:
“package ‘Seurat’ was built under R version 4.3.3”
Loading required package: SeuratObject

Warning message:
“package ‘SeuratObject’ was built under R version 4.3.3”
Loading required package: sp

Warning message:
“package ‘sp’ was built under R version 4.3.2”

Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, t


Warning message:
“package ‘dplyr’ was built under R version 4.3.2”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:
# "indir" is a custom input path, and "outdir" is a custom output path.
# indir=""
# outdir=""

In [ ]:
aging_DHMR_state <- read.csv(paste0(indir,"/DHMR.subclass_diff_hyper_hypo_info.csv"))

In [3]:
head(aging_DHMR_state);dim(aging_DHMR_state)

  cluster          chrom                   diff       hyper_hypo
1 STR D2 Gaba      chr10_19079768_19080172 0.05241002 1
2 L2/3 IT CTX Glut chr10_19083814_19084821 0.05317036 1
3 L5 IT CTX Glut   chr10_19083814_19084821 0.05825865 1
4 L2/3 IT CTX Glut chr10_19088362_19088651 0.05967491 1
5 L5 IT CTX Glut   chr10_19088362_19088651 0.06126827 1
6 L6 CT CTX Glut   chr10_19088362_19088651 0.08662094 1

[1] 862371      4

In [4]:
unique(aging_DHMR_state$cluster)

 [1] "STR D2 Gaba"           "L2/3 IT CTX Glut"      "L5 IT CTX Glut"
 [4] "L6 CT CTX Glut"        "L4/5 IT CTX Glut"      "Astro-TE NN"
 [7] "OB-in Frmd7 Gaba"      "CA1-ProS Glut"         "DG Glut"
[10] "CA3 Glut"              "Oligo NN"              "L5 ET CTX Glut"
[13] "OPC NN"                "L2/3 IT RSP Glut"      "CLA-EPd-CTX Car3 Glut"
[16] "Pvalb Gaba"            "ACB-BST-FS D1 Gaba"    "OB Eomes Ms4a15 Glut"
[19] "Microglia NN"          "IT AON-TT-DP Glut"     "STR D1 Sema5a Gaba"
[22] "OEC NN"                "Lamp5 Gaba"            "OB-out Frmd7 Gaba"
[25] "L5 NP CTX Glut"

In [5]:
range(aging_DHMR_state$diff)

[1] -0.4097222  0.6282051

In [6]:
aging_DHMR_state_filter <- aging_DHMR_state %>%
  mutate(
    start = as.numeric(gsub(".*_(\\d+)_.*", "\\1", chrom)),
    end = as.numeric(gsub(".*_(\\d+)$", "\\1", chrom)),
    length = end - start
  ) %>%
  filter(length >= 200) %>%
  select(-start, -end, -length)

In [7]:
head(aging_DHMR_state_filter);dim(aging_DHMR_state_filter)
range(aging_DHMR_state_filter$diff)

  cluster          chrom                   diff       hyper_hypo
1 STR D2 Gaba      chr10_19079768_19080172 0.05241002 1
2 L2/3 IT CTX Glut chr10_19083814_19084821 0.05317036 1
3 L5 IT CTX Glut   chr10_19083814_19084821 0.05825865 1
4 L2/3 IT CTX Glut chr10_19088362_19088651 0.05967491 1
5 L5 IT CTX Glut   chr10_19088362_19088651 0.06126827 1
6 L6 CT CTX Glut   chr10_19088362_19088651 0.08662094 1

[1] 862371      4

[1] -0.4097222  0.6282051

In [8]:
length(aging_DHMR_state_filter$chrom);length(unique(aging_DHMR_state_filter$chrom))

[1] 862371

[1] 397462

In [ ]:
aging_DMR_state <- read.csv(paste0(indir,"/DMR.subclass_diff_hyper_hypo_info.csv"))

In [10]:
head(aging_DMR_state);dim(aging_DMR_state)

  cluster           chrom                     diff        hyper_hypo
1 Astro-TE NN       chr10_116773842_116774043  0.05631680 1
2 Oligo NN          chr10_116773842_116774043  0.13123035 1
3 CA1-ProS Glut     chr10_116777666_116778193  0.05733144 1
4 IT AON-TT-DP Glut chr10_116783966_116784267 -0.18278680 0
5 DG Glut           chr10_116783966_116784267  0.06137030 1
6 CA1-ProS Glut     chr10_116786645_116786863  0.05152750 1

[1] 476145      4

In [11]:
range(aging_DMR_state$diff)

[1] -0.6750000  0.6615384

In [12]:
aging_DMR_state_filter <- aging_DMR_state %>%
  mutate(
    start = as.numeric(gsub(".*_(\\d+)_.*", "\\1", chrom)),
    end = as.numeric(gsub(".*_(\\d+)$", "\\1", chrom)),
    length = end - start
  ) %>%
  filter(length >= 200) %>%
  select(-start, -end, -length)

In [13]:
head(aging_DMR_state_filter);dim(aging_DMR_state_filter)
range(aging_DMR_state_filter$diff)

  cluster           chrom                     diff        hyper_hypo
1 Astro-TE NN       chr10_116773842_116774043  0.05631680 1
2 Oligo NN          chr10_116773842_116774043  0.13123035 1
3 CA1-ProS Glut     chr10_116777666_116778193  0.05733144 1
4 IT AON-TT-DP Glut chr10_116783966_116784267 -0.18278680 0
5 DG Glut           chr10_116783966_116784267  0.06137030 1
6 CA1-ProS Glut     chr10_116786645_116786863  0.05152750 1

[1] 476145      4

[1] -0.6750000  0.6615384

In [14]:
length(aging_DMR_state_filter$chrom);length(unique(aging_DMR_state_filter$chrom))

[1] 476145

[1] 345543

In [15]:
aging_DHMR_state_final <- aging_DHMR_state_filter %>%
  group_by(cluster) %>%
  summarize(
    Specific_Hyper_Region = list(unique(chrom[hyper_hypo == 1 & !(chrom %in% aging_DHMR_state$chrom[aging_DHMR_state$cluster != cluster & aging_DHMR_state$hyper_hypo == 1])])),
    Specific_Hyper_Count = length(Specific_Hyper_Region[[1]]),
    Specific_Hypo_Region = list(unique(chrom[hyper_hypo == 0 & !(chrom %in% aging_DHMR_state$chrom[aging_DHMR_state$cluster != cluster & aging_DHMR_state$hyper_hypo == 0])])),
    Specific_Hypo_Count = length(Specific_Hypo_Region[[1]])
  ) %>%
  rename(Subclass = cluster) %>%
  mutate(
    Specific_Hyper_Region = sapply(Specific_Hyper_Region, function(x) paste0("['", paste(x, collapse = "', '"), "']")),
    Specific_Hypo_Region = sapply(Specific_Hypo_Region, function(x) paste0("['", paste(x, collapse = "', '"), "']"))
  )

Warning message:
“There were 46 warnings in `summarize()`.
The first warning was:
ℹ In argument: `Specific_Hyper_Region = list(...)`.
ℹ In group 1: `cluster = "ACB-BST-FS D1 Gaba"`.
Caused by warning in `aging_DHMR_state$cluster != cluster`:
! longer object length is not a multiple of shorter object length
ℹ Run `dplyr::last_dplyr_warnings()` to see the 45 remaining warnings.”

In [ ]:
write.csv(aging_DHMR_state_final, paste0(outdir,"/01-dhmr_specific_hyper_hypo_DHMR_include_region.csv"))

In [17]:
aging_DMR_state_final <- aging_DMR_state_filter %>%
  group_by(cluster) %>%
  summarize(
    Specific_Hyper_Region = list(unique(chrom[hyper_hypo == 1 & !(chrom %in% aging_DMR_state$chrom[aging_DMR_state$cluster != cluster & aging_DMR_state$hyper_hypo == 1])])),
    Specific_Hyper_Count = length(Specific_Hyper_Region[[1]]),
    Specific_Hypo_Region = list(unique(chrom[hyper_hypo == 0 & !(chrom %in% aging_DMR_state$chrom[aging_DMR_state$cluster != cluster & aging_DMR_state$hyper_hypo == 0])])),
    Specific_Hypo_Count = length(Specific_Hypo_Region[[1]])
  ) %>%
  rename(Subclass = cluster) %>%
  mutate(
    Specific_Hyper_Region = sapply(Specific_Hyper_Region, function(x) paste0("['", paste(x, collapse = "', '"), "']")),
    Specific_Hypo_Region = sapply(Specific_Hypo_Region, function(x) paste0("['", paste(x, collapse = "', '"), "']"))
  )

Warning message:
“There were 46 warnings in `summarize()`.
The first warning was:
ℹ In argument: `Specific_Hyper_Region = list(...)`.
ℹ In group 1: `cluster = "ACB-BST-FS D1 Gaba"`.
Caused by warning in `aging_DMR_state$cluster != cluster`:
! longer object length is not a multiple of shorter object length
ℹ Run `dplyr::last_dplyr_warnings()` to see the 45 remaining warnings.”

In [ ]:
write.csv(aging_DMR_state_final, paste0(outdir,"/01-dmr_specific_hyper_hypo_DMR_include_region.csv"))